import { createHash } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { DAILY_SCORING_POLICY, scoreEvaluation, type DailyMarket, type DailyPrediction } from "@/domain/market-v2/daily-analysis";

const token=(...values:string[])=>createHash("sha256").update(values.join("\0")).digest("hex");
function prediction(value:string|null):DailyPrediction|null{if(!value)return null;try{const x=JSON.parse(value) as Record<string,unknown>;if(![x.home,x.draw,x.away,x.contextualAgreement].every((v)=>typeof v==="number"))return null;return {home:Number(x.home),draw:Number(x.draw),away:Number(x.away),...(typeof x.over25==="number"?{over25:x.over25}:{}),...(typeof x.under25==="number"?{under25:x.under25}:{}),contextualAgreement:Number(x.contextualAgreement),contradictory:x.contradictory===true,rawSignals:{derivedFromFrozenRun:true}}}catch{return null}}

export type DerivedRunResult=Readonly<{runId:string;sportsDate:string;oddsResponseReceived:boolean;oddsEventsReceived:number;oddsFixturesMatched:number;oddsMarketsMatched:number;usableOddsAvailable:boolean;marketEvaluationsCreated:number;historicalDatasetFound:boolean;historicalMarketsCalibrated:number;historicalCalibrationAvailable:boolean;provisionalCandidates:number;strong:number;interesting:number;watch:number;pass:number;noPublishableRecommendations:boolean;replayed:boolean}>;

export async function deriveDailyRun(databaseUrl:string,sourceRunId:string):Promise<DerivedRunResult>{
  const prisma=new PrismaClient({datasourceUrl:databaseUrl});
  try{
    const source=await prisma.dailyAnalysisRun.findUnique({where:{id:sourceRunId},include:{requestAudits:true,evidence:true,exclusions:true,candidates:{include:{fixture:true,evaluations:true,recommendations:true}}}});if(!source)throw new Error("SOURCE_RUN_NOT_FOUND");
    const historicalDatasetFound=await prisma.historicalDataset.count()>0;
    const runId=`derived-${token(sourceRunId,DAILY_SCORING_POLICY.version,"offline-19b").slice(0,32)}`;
    const existing=await prisma.dailyAnalysisRun.findUnique({where:{id:runId},include:{candidates:{include:{recommendations:true}}}});if(existing)return result(existing,existing.candidates.flatMap((c)=>c.recommendations.map((r)=>r.classification)),true);
    const oddsAudit=source.requestAudits.find((audit)=>audit.providerId==="provider-the-odds-api");
    const oddsResponseReceived=oddsAudit?.classification==="SUCCESS"&&oddsAudit.httpStatus!==null;
    const prepared=source.candidates.map((candidate)=>{
      const pred=prediction(candidate.predictionJson);const probabilities=pred?[pred.home,pred.draw,pred.away].sort((a,b)=>b-a):[];const topMargin=probabilities.length?probabilities[0]-probabilities[1]:0;
      const selected=candidate.recommendations[0];const selectedEval=selected?candidate.evaluations.find((evaluation)=>evaluation.id===selected.marketEvaluationId):undefined;
      const scored=pred&&selectedEval?.modelProbability!==null&&selectedEval?.modelProbability!==undefined?scoreEvaluation({market:selectedEval.market as DailyMarket,probability:Number(selectedEval.modelProbability),topMargin:["HOME","DRAW","AWAY"].includes(selectedEval.market)?topMargin:.1,dataQuality:Number(candidate.dataQuality),contextualAgreement:pred.contextualAgreement,contradictory:pred.contradictory,historicalSample:0,edge:null,expectedValue:null,dispersion:null}):null;
      return {candidate,pred,selected,selectedEval,scored};
    });
    const ranked=prepared.filter((item)=>item.scored&&item.selectedEval).sort((a,b)=>b.scored!.total-a.scored!.total||b.pred![a.selectedEval!.market==="HOME"?"home":a.selectedEval!.market==="DRAW"?"draw":"away"]-a.pred![b.selectedEval!.market==="HOME"?"home":b.selectedEval!.market==="DRAW"?"draw":"away"]||a.candidate.fixture.kickoffAtUtc.valueOf()-b.candidate.fixture.kickoffAtUtc.valueOf());
    const ranks=new Map(ranked.map((item,index)=>[item.candidate.id,index+1]));const marketEvaluationsCreated=prepared.reduce((sum,item)=>sum+item.candidate.evaluations.length,0);
    await prisma.$transaction(async(tx)=>{
      await tx.dailyAnalysisRun.create({data:{id:runId,derivedFromRunId:source.id,sportsDate:source.sportsDate,mode:"MODEL_ONLY_PROVISIONAL",status:"COMPLETED",scoringPolicyVersion:DAILY_SCORING_POLICY.version,startedAtUtc:new Date(),completedAtUtc:new Date(),historicalCalibrationAvailable:false,historicalDatasetFound,historicalMarketsCalibrated:0,oddsAvailable:false,oddsResponseReceived,oddsEventsReceived:0,oddsFixturesMatched:0,oddsMarketsMatched:0,usableOddsAvailable:false,marketEvaluationsCreated,oddsDiagnosticsJson:JSON.stringify(source.candidates.filter((c)=>c.deepAnalyzed).map((c)=>({fixtureId:c.fixtureId,code:oddsResponseReceived?"ODDS_EVENT_NOT_FOUND":"ODDS_PROVIDER_UNAVAILABLE",method:"offline-derived/1.0.0",warnings:[]}))),marketValueCalculated:false,fixturesDiscovered:source.fixturesDiscovered,fixturesEligible:source.fixturesEligible,fixturesDeepAnalyzed:source.fixturesDeepAnalyzed,fixturesExcluded:source.fixturesExcluded,recommendations:ranked.length,apiFootballBudget:0,apiFootballRequests:0,oddsBudget:0,oddsRequests:0,warningsJson:JSON.stringify(["MODEL_ONLY_PROVISIONAL","MISSING_HISTORY",oddsResponseReceived?"ODDS_RESPONSE_WITHOUT_USABLE_MATCH":"ODDS_PROVIDER_UNAVAILABLE","NO_PUBLISHABLE_RECOMMENDATIONS","DERIVED_OFFLINE_NO_NETWORK"])}});
      for(const item of prepared){const candidateId=`cand-${token(runId,item.candidate.fixtureId).slice(0,24)}`;await tx.dailyFixtureCandidate.create({data:{id:candidateId,runId,fixtureId:item.candidate.fixtureId,eligible:item.candidate.eligible,deepAnalyzed:item.candidate.deepAnalyzed,discoveryOrdinal:item.candidate.discoveryOrdinal,dataQuality:item.candidate.dataQuality,predictionJson:item.candidate.predictionJson,reasonsJson:item.candidate.reasonsJson,warningsJson:item.candidate.warningsJson}});for(const evaluation of item.candidate.evaluations){const evalId=`eval-${token(candidateId,evaluation.market).slice(0,24)}`;await tx.dailyMarketEvaluation.create({data:{id:evalId,candidateId,market:evaluation.market,evaluationStatus:"MODEL_ONLY",modelProbability:evaluation.modelProbability,fairOdds:evaluation.modelProbability?1/Number(evaluation.modelProbability):null,bestMarketOdds:null,marketImpliedProbability:null,marketMargin:null,noVigProbability:null,edge:null,expectedValue:null,bookmakerDispersion:null,bookmakerCount:0,consensusOdds:null,historicalSample:0,datasetVersion:null,calibrationStatus:"MISSING_HISTORY",matchingJson:JSON.stringify({code:oddsResponseReceived?"ODDS_EVENT_NOT_FOUND":"ODDS_PROVIDER_UNAVAILABLE",method:"offline-derived/1.0.0"}),reasonsJson:JSON.stringify(["MODEL_SIGNAL_AVAILABLE"]),warningsJson:JSON.stringify(["MISSING_HISTORY","ODDS_PRICE_UNAVAILABLE"])}});if(item.selectedEval?.id===evaluation.id&&item.scored){const [m,h,v,c,q]=item.scored.components;await tx.dailyRecommendation.create({data:{id:`rec-${token(evalId).slice(0,24)}`,candidateId,marketEvaluationId:evalId,rank:ranks.get(item.candidate.id)!,market:evaluation.market,recommendationStatus:"MODEL_ONLY_PROVISIONAL",classification:item.scored.classification,reviewStatus:"PENDING_REVIEW",scoreTotal:item.scored.total,modelConfidenceScore:m,historicalCalibrationScore:h,marketValueScore:v,contextualAgreementScore:c,dataQualityScore:q,penaltiesTotal:m+h+v+c+q-item.scored.total,explanationJson:JSON.stringify(["CANDIDATO_PROVISIONAL",...item.scored.penalties]),risksJson:JSON.stringify(["MISSING_HISTORY","ODDS_PRICE_UNAVAILABLE"])}})}}}
      for(const exclusion of source.exclusions)await tx.dailyExclusion.create({data:{id:`exc-${token(runId,exclusion.id).slice(0,24)}`,runId,providerFixtureId:exclusion.providerFixtureId,fixtureLabel:exclusion.fixtureLabel,reasonCode:exclusion.reasonCode,detailsJson:exclusion.detailsJson}});
      for(const evidence of source.evidence)await tx.dailyRawEvidence.create({data:{id:`ev-${token(runId,evidence.contentHash,evidence.endpointKey).slice(0,24)}`,runId,providerKey:evidence.providerKey,endpointKey:evidence.endpointKey,capturedAtUtc:evidence.capturedAtUtc,contentHash:evidence.contentHash,byteLength:evidence.byteLength,mediaType:evidence.mediaType,storageReference:evidence.storageReference}});
    });
    const created=await prisma.dailyAnalysisRun.findUniqueOrThrow({where:{id:runId},include:{candidates:{include:{recommendations:true}}}});return result(created,created.candidates.flatMap((c)=>c.recommendations.map((r)=>r.classification)),false);
  }finally{await prisma.$disconnect()}
}

function result(run:{id:string;sportsDate:string;oddsResponseReceived:boolean;oddsEventsReceived:number;oddsFixturesMatched:number;oddsMarketsMatched:number;usableOddsAvailable:boolean;marketEvaluationsCreated:number;historicalDatasetFound:boolean;historicalMarketsCalibrated:number;historicalCalibrationAvailable:boolean},classes:readonly string[],replayed:boolean):DerivedRunResult{const count=(value:string)=>classes.filter((item)=>item===value).length;return {runId:run.id,sportsDate:run.sportsDate,oddsResponseReceived:run.oddsResponseReceived,oddsEventsReceived:run.oddsEventsReceived,oddsFixturesMatched:run.oddsFixturesMatched,oddsMarketsMatched:run.oddsMarketsMatched,usableOddsAvailable:run.usableOddsAvailable,marketEvaluationsCreated:run.marketEvaluationsCreated,historicalDatasetFound:run.historicalDatasetFound,historicalMarketsCalibrated:run.historicalMarketsCalibrated,historicalCalibrationAvailable:run.historicalCalibrationAvailable,provisionalCandidates:classes.length,strong:count("STRONG"),interesting:count("INTERESTING"),watch:count("WATCH"),pass:count("PASS"),noPublishableRecommendations:count("STRONG")+count("INTERESTING")===0,replayed}}
