import { createHash } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { DAILY_SCORING_POLICY,evaluateMarkets,scoreEvaluation,type DailyMarket,type DailyPrediction,type MarketQuote } from "@/domain/market-v2/daily-analysis";
import { matchOddsFixtureV2,ODDS_MATCHING_V2_POLICY,type CanonicalOddsFixture,type OddsIdentityEvent } from "@/domain/market-v2/odds-matching-v2";
import { mapPriceableOdds } from "@/domain/market-v2/odds-market-mapping";
import { PROVIDER_TEAM_ALIAS_REGISTRY_VERSION,type ProviderTeamAliasRecord } from "@/domain/market-v2/provider-team-alias";
import { readVerifiedOddsEvidence } from "./team-alias-workflow";

const token=(...values:readonly string[])=>createHash("sha256").update(values.join("\0")).digest("hex");
const numberOrUndefined=(value:unknown):number|undefined=>typeof value==="number"&&Number.isFinite(value)?value:undefined;
const MARKETS:readonly DailyMarket[]=["HOME","DRAW","AWAY","1X","X2","12","OVER_15","UNDER_15","OVER_25","UNDER_25"];
export type AliasReplaySummary=Readonly<{runId:string;sourceRunId:string;events:number;matchedExact:number;matchedAlias:number;unmatched:number;ambiguous:number;h2hMarketsMatched:number;totals25MarketsMatched:number;doubleChanceOffered:boolean;usableOddsCount:number;fairOddsCalculated:number;noVigCalculated:number;edgeCalculated:number;evCalculated:number;watch:number;provisionalCandidates:number;pass:number;replayed:boolean}>;

export async function replayDailyOddsWithAliases(input:Readonly<{databaseUrl:string;runId:string;evidenceRoot:string}>):Promise<AliasReplaySummary>{
  const db=new PrismaClient({datasourceUrl:input.databaseUrl});try{
    const source=await db.dailyAnalysisRun.findUnique({where:{id:input.runId},include:{evidence:true,exclusions:true,candidates:{where:{deepAnalyzed:true,predictionJson:{not:null}},orderBy:{discoveryOrdinal:"asc"},include:{fixture:{include:{homeTeam:true,awayTeam:true,providerIdentities:{where:{providerId:"provider-api-football"}}}},recommendations:{orderBy:{rank:"asc"}}}}}});if(!source)throw new Error("RUN_NOT_FOUND");
    const artifact=source.evidence.find(value=>value.providerKey==="the-odds-api");if(!artifact)throw new Error("ODDS_EVIDENCE_NOT_FOUND");const verified=await readVerifiedOddsEvidence(input.evidenceRoot,artifact.storageReference,artifact.contentHash);
    const aliasRows=await db.providerTeamAlias.findMany({where:{providerKey:"the-odds-api",status:"APPROVED",registryVersion:PROVIDER_TEAM_ALIAS_REGISTRY_VERSION},orderBy:{id:"asc"}});const aliases:ProviderTeamAliasRecord[]=aliasRows.map(row=>({...row,status:"APPROVED"}));
    const runId=`alias-replay-${token(source.id,verified.hash,ODDS_MATCHING_V2_POLICY.version,PROVIDER_TEAM_ALIAS_REGISTRY_VERSION,...aliases.map(alias=>alias.id)).slice(0,32)}`;
    const existing=await db.dailyAnalysisRun.findUnique({where:{id:runId},include:{candidates:{include:{evaluations:true,recommendations:true}}}});if(existing){const evaluations=existing.candidates.flatMap(candidate=>candidate.evaluations),recommendations=existing.candidates.flatMap(candidate=>candidate.recommendations);return Object.freeze({runId,sourceRunId:source.id,events:existing.oddsEventsReceived,matchedExact:existing.fixturesMatchedExact,matchedAlias:existing.fixturesMatchedAlias,unmatched:existing.fixturesUnmatched,ambiguous:existing.fixturesAmbiguous,h2hMarketsMatched:existing.h2hMarketsMatched,totals25MarketsMatched:existing.totals25MarketsMatched,doubleChanceOffered:existing.doubleChanceOffered,usableOddsCount:existing.usableOddsCount,fairOddsCalculated:evaluations.filter(value=>value.fairOdds!==null).length,noVigCalculated:evaluations.filter(value=>value.noVigProbability!==null).length,edgeCalculated:evaluations.filter(value=>value.edge!==null).length,evCalculated:evaluations.filter(value=>value.expectedValue!==null).length,watch:recommendations.filter(value=>value.classification==="WATCH").length,provisionalCandidates:recommendations.filter(value=>value.recommendationStatus.includes("PROVISIONAL")).length,pass:recommendations.filter(value=>value.classification==="PASS").length,replayed:true})}
    const identities:OddsIdentityEvent[]=verified.events.map(event=>({id:event.id,homeName:event.home_team,awayName:event.away_team,kickoffAtUtc:event.commence_time,sportKey:event.sport_key,sportTitle:event.sport_title}));
    type Item=typeof source.candidates[number];type Evaluated=Readonly<{item:Item;fixture:CanonicalOddsFixture;prediction:DailyPrediction;match:ReturnType<typeof matchOddsFixtureV2>;quotes:readonly MarketQuote[];unsupported:readonly string[];evaluations:ReturnType<typeof evaluateMarkets>;suggestedMarket:DailyMarket;bestPricedMarket:DailyMarket|null;scored:ReturnType<typeof scoreEvaluation>;classification:"WATCH"|"PASS"}>;
    const prepared:Evaluated[]=[];let matchedExact=0,matchedAlias=0,ambiguous=0,unmatched=0,h2hMarketsMatched=0,totals25MarketsMatched=0,usableOddsCount=0;let doubleChanceOffered=verified.events.some(event=>event.bookmakers.some(bookmaker=>bookmaker.markets.some(market=>market.key==="double_chance")));
    for(const item of source.candidates){const identity=item.fixture.providerIdentities[0];if(!identity)throw new Error("CANONICAL_BINDING_MISSING");const fixture:CanonicalOddsFixture={fixtureId:identity.providerFixtureId,homeTeamId:item.fixture.homeTeamId,awayTeamId:item.fixture.awayTeamId,homeName:item.fixture.homeTeam.displayName,awayName:item.fixture.awayTeam.displayName,kickoffAtUtc:item.fixture.kickoffAtUtc.toISOString(),country:item.fixture.country,competitionName:item.fixture.competitionName};const match=matchOddsFixtureV2(fixture,identities,aliases,artifact.id);if(match.code==="MATCHED_EXACT")matchedExact+=1;else if(match.code==="MATCHED_APPROVED_ALIAS")matchedAlias+=1;else if(match.code==="TEAM_ALIAS_AMBIGUOUS"||match.code==="MULTIPLE_EVENTS")ambiguous+=1;else unmatched+=1;
      const event=match.matchedEventId?verified.events.find(value=>value.id===match.matchedEventId):undefined;const mapped=event?mapPriceableOdds(event):{quotes:[],matchedMarkets:[],unsupportedMarketKeys:[],doubleChanceOffered:false};doubleChanceOffered=doubleChanceOffered||mapped.doubleChanceOffered;usableOddsCount+=mapped.quotes.length;h2hMarketsMatched+=mapped.matchedMarkets.filter(market=>["HOME","DRAW","AWAY"].includes(market)).length;totals25MarketsMatched+=mapped.matchedMarkets.filter(market=>market==="OVER_25"||market==="UNDER_25").length;
      const raw=JSON.parse(item.predictionJson!) as Record<string,unknown>,home=numberOrUndefined(raw.home),draw=numberOrUndefined(raw.draw),away=numberOrUndefined(raw.away);if(home===undefined||draw===undefined||away===undefined)throw new Error("PERSISTED_PREDICTION_INVALID");const prediction:DailyPrediction={home,draw,away,over15:numberOrUndefined(raw.over15),under15:numberOrUndefined(raw.under15),over25:numberOrUndefined(raw.over25),under25:numberOrUndefined(raw.under25),winner:typeof raw.winner==="string"?raw.winner:null,advice:typeof raw.advice==="string"?raw.advice:null,contextualAgreement:numberOrUndefined(raw.contextualAgreement)??0,contradictory:raw.contradictory===true,rawSignals:{source:"PERSISTED",sourceRunId:source.id}};const evaluations=evaluateMarkets(prediction,mapped.quotes);const sourceSuggested=item.recommendations[0]?.modelSuggestedMarket??item.recommendations[0]?.market;const suggestedMarket=MARKETS.includes(sourceSuggested as DailyMarket)?sourceSuggested as DailyMarket:"HOME";const suggested=evaluations.find(value=>value.market===suggestedMarket);if(!suggested?.modelProbability)throw new Error("MODEL_SUGGESTED_MARKET_INVALID");const priced=evaluations.filter(value=>value.bestMarketOdds!==null&&value.modelProbability!==null).sort((a,b)=>(b.expectedValue??-Infinity)-(a.expectedValue??-Infinity)||a.market.localeCompare(b.market));const bestPricedMarket=priced[0]?.market??null;const top=[home,draw,away].sort((a,b)=>b-a),scored=scoreEvaluation({market:suggestedMarket,probability:suggested.modelProbability,topMargin:["HOME","DRAW","AWAY"].includes(suggestedMarket)?top[0]-top[1]:.1,dataQuality:Number(item.dataQuality),contextualAgreement:prediction.contextualAgreement,contradictory:prediction.contradictory,historicalSample:0,edge:suggested.edge,expectedValue:suggested.expectedValue,dispersion:suggested.dispersion});const watchAllowed=suggested.bestMarketOdds!==null&&suggested.edge!==null&&suggested.edge>0&&suggested.expectedValue!==null&&suggested.expectedValue>0&&Number(item.dataQuality)>=DAILY_SCORING_POLICY.thresholds.minimumQuality;const classification=scored.classification==="WATCH"&&watchAllowed?"WATCH":"PASS";
      prepared.push({item,fixture,prediction,match,quotes:mapped.quotes,unsupported:mapped.unsupportedMarketKeys,evaluations,suggestedMarket,bestPricedMarket,scored,classification});
    }
    const ordered=[...prepared].sort((a,b)=>b.scored.total-a.scored.total||(b.evaluations.find(value=>value.market===b.suggestedMarket)?.modelProbability??0)-(a.evaluations.find(value=>value.market===a.suggestedMarket)?.modelProbability??0)||a.fixture.kickoffAtUtc.localeCompare(b.fixture.kickoffAtUtc)||a.fixture.fixtureId.localeCompare(b.fixture.fixtureId));const ranks=new Map(ordered.map((value,index)=>[value.item.id,index+1]));const evaluations=prepared.flatMap(value=>value.evaluations),diagnostics=prepared.map(value=>({fixtureId:value.fixture.fixtureId,...value.match,unsupportedMarketKeys:value.unsupported}));
    const started=new Date();await db.$transaction(async tx=>{await tx.dailyAnalysisRun.create({data:{id:runId,derivedFromRunId:source.id,sportsDate:source.sportsDate,mode:"MODEL_ONLY_PROVISIONAL",status:"COMPLETED",scoringPolicyVersion:DAILY_SCORING_POLICY.version,startedAtUtc:started,completedAtUtc:new Date(),historicalCalibrationAvailable:false,historicalDatasetHash:null,oddsAvailable:true,oddsResponseReceived:true,oddsEventsReceived:verified.events.length,oddsFixturesMatched:matchedExact+matchedAlias,oddsMarketsMatched:h2hMarketsMatched+totals25MarketsMatched,usableOddsAvailable:usableOddsCount>0,marketEvaluationsCreated:evaluations.length,oddsDiagnosticsJson:JSON.stringify(diagnostics),historicalDatasetFound:false,historicalMarketsCalibrated:0,aliasRegistryVersion:PROVIDER_TEAM_ALIAS_REGISTRY_VERSION,matcherVersion:ODDS_MATCHING_V2_POLICY.version,fixturesMatchedExact:matchedExact,fixturesMatchedAlias:matchedAlias,fixturesUnmatched:unmatched,fixturesAmbiguous:ambiguous,usableOddsCount,h2hMarketsMatched,totals25MarketsMatched,doubleChanceOffered,marketValueCalculated:evaluations.some(value=>value.edge!==null&&value.expectedValue!==null),fixturesDiscovered:source.fixturesDiscovered,fixturesEligible:prepared.length,fixturesDeepAnalyzed:prepared.length,fixturesExcluded:source.fixturesExcluded,recommendations:prepared.length,apiFootballBudget:0,apiFootballRequests:0,oddsBudget:0,oddsRequests:0,warningsJson:JSON.stringify(["OFFLINE_EVIDENCE_REPLAY","MISSING_HISTORY",...(doubleChanceOffered?[]:["DOUBLE_CHANCE_NOT_OFFERED"]),...(verified.events.some(event=>event.bookmakers.some(bookmaker=>bookmaker.markets.some(market=>market.key==="h2h_lay")))?["MARKET_UNSUPPORTED:h2h_lay"]:[]),"NO_PUBLISHABLE_RECOMMENDATIONS"])}});
      for(const exclusion of source.exclusions)await tx.dailyExclusion.create({data:{id:`exc-${token(runId,exclusion.id).slice(0,24)}`,runId,providerFixtureId:exclusion.providerFixtureId,fixtureLabel:exclusion.fixtureLabel,reasonCode:exclusion.reasonCode,detailsJson:exclusion.detailsJson}});
      for(const value of prepared){const candidateId=`cand-${token(runId,value.item.fixtureId).slice(0,24)}`;await tx.dailyFixtureCandidate.create({data:{id:candidateId,runId,fixtureId:value.item.fixtureId,eligible:true,deepAnalyzed:true,discoveryOrdinal:value.item.discoveryOrdinal,dataQuality:value.item.dataQuality,predictionJson:value.item.predictionJson,reasonsJson:value.item.reasonsJson,warningsJson:value.item.warningsJson}});for(const evaluation of value.evaluations){const evaluationId=`eval-${token(candidateId,evaluation.market).slice(0,24)}`,marketQuotes=value.quotes.filter(quote=>quote.market===evaluation.market),offered=evaluation.bestMarketOdds!==null;await tx.dailyMarketEvaluation.create({data:{id:evaluationId,candidateId,market:evaluation.market,evaluationStatus:evaluation.status,modelProbability:evaluation.modelProbability,fairOdds:evaluation.fairOdds,bestMarketOdds:evaluation.bestMarketOdds,marketImpliedProbability:evaluation.bestMarketOdds?1/evaluation.bestMarketOdds:null,marketMargin:evaluation.marketMargin,noVigProbability:evaluation.noVigProbability,edge:evaluation.edge,expectedValue:evaluation.expectedValue,bookmakerDispersion:evaluation.dispersion,bookmakerCount:evaluation.bookmakerCount,consensusOdds:evaluation.consensusOdds,historicalSample:0,datasetVersion:null,calibrationStatus:"MISSING_HISTORY",matchingJson:JSON.stringify({...value.match,market:evaluation.market,marketOffered:offered,bookmakersCount:new Set(marketQuotes.map(quote=>quote.bookmaker)).size}),offeredOddsStatus:offered?"OFFERED_ODDS_AVAILABLE":"OFFERED_ODDS_UNAVAILABLE",unsupportedMarketKeysJson:JSON.stringify(value.unsupported),reasonsJson:JSON.stringify(offered?["PRICEABLE_MARKET_MAPPED"]:["OFFERED_ODDS_UNAVAILABLE"]),warningsJson:JSON.stringify(["MISSING_HISTORY",...(offered?[]:["OFFERED_ODDS_UNAVAILABLE"]),...value.unsupported.map(key=>`MARKET_UNSUPPORTED:${key}`)])}});if(evaluation.market===value.suggestedMarket){const [model,historical,market,contextual,quality]=value.scored.components;await tx.dailyRecommendation.create({data:{id:`rec-${token(evaluationId).slice(0,24)}`,candidateId,marketEvaluationId:evaluationId,rank:ranks.get(value.item.id)!,market:value.suggestedMarket,recommendationStatus:value.classification==="WATCH"?"PROVISIONAL_WATCH":"MODEL_ONLY_PROVISIONAL",classification:value.classification,reviewStatus:"PENDING_REVIEW",scoreTotal:value.scored.total,modelConfidenceScore:model,historicalCalibrationScore:historical,marketValueScore:market,contextualAgreementScore:contextual,dataQualityScore:quality,penaltiesTotal:model+historical+market+contextual+quality-value.scored.total,explanationJson:JSON.stringify([value.classification==="WATCH"?"WATCH_PROVISIONAL":"PROVISIONAL_CANDIDATE",...value.scored.penalties]),risksJson:JSON.stringify(["MISSING_HISTORY",...(offered?[]:["MARKET_SUGGESTED_WITHOUT_QUOTE"])]),modelSuggestedMarket:value.suggestedMarket,bestPricedMarket:value.bestPricedMarket}})}}}
      await tx.dailyRawEvidence.create({data:{id:`ev-${token(runId,artifact.contentHash).slice(0,24)}`,runId,providerKey:artifact.providerKey,endpointKey:artifact.endpointKey,capturedAtUtc:artifact.capturedAtUtc,contentHash:artifact.contentHash,byteLength:artifact.byteLength,mediaType:artifact.mediaType,storageReference:artifact.storageReference}})});
    const summary:AliasReplaySummary={runId,sourceRunId:source.id,events:verified.events.length,matchedExact,matchedAlias,unmatched,ambiguous,h2hMarketsMatched,totals25MarketsMatched,doubleChanceOffered,usableOddsCount,fairOddsCalculated:evaluations.filter(value=>value.fairOdds!==null).length,noVigCalculated:evaluations.filter(value=>value.noVigProbability!==null).length,edgeCalculated:evaluations.filter(value=>value.edge!==null).length,evCalculated:evaluations.filter(value=>value.expectedValue!==null).length,watch:prepared.filter(value=>value.classification==="WATCH").length,provisionalCandidates:prepared.length,pass:prepared.filter(value=>value.classification==="PASS").length,replayed:false};return Object.freeze(summary);
  }finally{await db.$disconnect()}
}
