import { createHash } from "node:crypto";
import { readFile,realpath } from "node:fs/promises";
import { isAbsolute,relative,resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
import { z } from "zod";
import { aliasScopeKey,findAliasCollision,normalizeProviderTeamName,PROVIDER_TEAM_ALIAS_REGISTRY_VERSION,toAliasRecord,type AliasProposal,type ProviderTeamAliasRecord } from "@/domain/market-v2/provider-team-alias";
import { ODDS_MATCHING_V2_POLICY } from "@/domain/market-v2/odds-matching-v2";

const outcomeSchema=z.object({name:z.string(),price:z.number(),point:z.number().optional()}).passthrough();
const eventSchema=z.object({id:z.string(),sport_key:z.string().optional(),sport_title:z.string().optional(),commence_time:z.iso.datetime({offset:true}),home_team:z.string(),away_team:z.string(),bookmakers:z.array(z.object({key:z.string(),title:z.string(),markets:z.array(z.object({key:z.string(),outcomes:z.array(outcomeSchema)}).passthrough())}).passthrough())}).passthrough();
export type StoredOddsEvent=z.infer<typeof eventSchema>;
const approvalSchema=z.object({canonicalTeamId:z.string().min(1),providerKey:z.literal("the-odds-api"),providerAliasRaw:z.string().min(1).refine(value=>!value.includes("*")&&!/^\/.+\/[a-z]*$/iu.test(value),"literal alias required"),countryScope:z.string().min(1).nullable(),competitionScope:z.string().min(1).nullable(),sourceArtifactId:z.string().min(1),decision:z.enum(["APPROVED","REJECTED"])}).strict();

export async function readVerifiedOddsEvidence(evidenceRoot:string,storageReference:string,expectedHash:string):Promise<Readonly<{events:readonly StoredOddsEvent[];hash:string;bytes:number}>>{
  if(!isAbsolute(evidenceRoot)||isAbsolute(storageReference))throw new Error("EVIDENCE_PATH_INVALID");
  const root=await realpath(evidenceRoot),path=resolve(root,storageReference),rel=relative(root,path);if(rel!==storageReference||rel.startsWith(".."))throw new Error("EVIDENCE_PATH_INVALID");
  const before=await readFile(path),beforeHash=createHash("sha256").update(before).digest("hex");if(beforeHash!==expectedHash)throw new Error("EVIDENCE_HASH_MISMATCH");
  const parsed=z.array(eventSchema).safeParse(JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(before)));if(!parsed.success)throw new Error("EVIDENCE_ENVELOPE_INVALID");
  const after=await readFile(path),afterHash=createHash("sha256").update(after).digest("hex");if(afterHash!==beforeHash)throw new Error("EVIDENCE_CHANGED_DURING_READ");
  return Object.freeze({events:Object.freeze(parsed.data),hash:beforeHash,bytes:before.byteLength});
}

function competitionCoherent(fixture:Readonly<{country:string;competitionName:string}>,event:StoredOddsEvent):boolean{
  const title=normalizeProviderTeamName(event.sport_title??""),country=normalizeProviderTeamName(fixture.country),competition=normalizeProviderTeamName(fixture.competitionName);
  return Boolean(title)&&(title.includes(country)||country.includes(title)||competition.split(" ").filter(token=>token.length>3).some(token=>title.includes(token)));
}

export async function proposeTeamAliases(input:Readonly<{databaseUrl:string;runId:string;evidenceRoot:string}>):Promise<Readonly<{runId:string;events:number;proposals:number;created:number;matrix:readonly unknown[]}>>{
  const db=new PrismaClient({datasourceUrl:input.databaseUrl});try{
    const run=await db.dailyAnalysisRun.findUnique({where:{id:input.runId},include:{evidence:true,candidates:{where:{deepAnalyzed:true},include:{fixture:{include:{homeTeam:true,awayTeam:true,providerIdentities:{where:{providerId:"provider-api-football"}}}}}}}});if(!run)throw new Error("RUN_NOT_FOUND");
    const artifact=run.evidence.find(value=>value.providerKey==="the-odds-api");if(!artifact)throw new Error("ODDS_EVIDENCE_NOT_FOUND");const verified=await readVerifiedOddsEvidence(input.evidenceRoot,artifact.storageReference,artifact.contentHash);
    const proposals:AliasProposal[]=[];const matrix:unknown[]=[];
    for(const candidate of run.candidates){const fixture=candidate.fixture,identity=fixture.providerIdentities[0];if(!identity)throw new Error("CANONICAL_BINDING_MISSING");const football=verified.events.filter(event=>event.sport_key?.startsWith("soccer_"));const within=football.map(event=>({event,deltaSeconds:Math.abs(Date.parse(event.commence_time)-fixture.kickoffAtUtc.getTime())/1000})).filter(value=>value.deltaSeconds<=ODDS_MATCHING_V2_POLICY.kickoffToleranceMinutes*60);const coherent=within.filter(value=>competitionCoherent(fixture,value.event));const unique=coherent.length===1?coherent[0]:null;const proposed:AliasProposal[]=[];
      if(unique){for(const team of [{id:fixture.homeTeamId,canonical:fixture.homeTeam.displayName,provider:unique.event.home_team,side:"HOME"},{id:fixture.awayTeamId,canonical:fixture.awayTeam.displayName,provider:unique.event.away_team,side:"AWAY"}] as const)if(normalizeProviderTeamName(team.canonical)!==normalizeProviderTeamName(team.provider)){const proposal:AliasProposal={canonicalTeamId:team.id,canonicalName:team.canonical,providerKey:"the-odds-api",providerAliasRaw:team.provider,countryScope:fixture.country,competitionScope:fixture.competitionName,sourceArtifactId:artifact.id,evidence:{fixtureId:identity.providerFixtureId,eventId:unique.event.id,side:team.side,kickoffDeltaSeconds:unique.deltaSeconds,orientation:"DIRECT",sportKey:unique.event.sport_key??null,sportTitle:unique.event.sport_title??null,marketKeys:[...new Set(unique.event.bookmakers.flatMap(bookmaker=>bookmaker.markets.map(market=>market.key)))].sort()}};proposals.push(proposal);proposed.push(proposal)}}
      matrix.push({fixtureId:identity.providerFixtureId,home:fixture.homeTeam.displayName,away:fixture.awayTeam.displayName,kickoffAtUtc:fixture.kickoffAtUtc.toISOString(),competition:fixture.competitionName,country:fixture.country,timeCandidates:within.length,scopeCoherentCandidates:coherent.length,decision:unique?"UNIQUE_SCOPED_EVENT":"NO_INEQUIVOCAL_EVENT",proposedAliases:proposed.map(value=>({canonical:value.canonicalName,provider:value.providerAliasRaw}))});
    }
    let created=0;for(const proposal of proposals){const record=toAliasRecord(proposal,"PROPOSED","OFFLINE_UNIQUE_FIXTURE_PROPOSAL");const exists=await db.providerTeamAlias.findUnique({where:{providerKey_providerAliasNormalized_scopeKey_canonicalTeamId_status_registryVersion:{providerKey:record.providerKey,providerAliasNormalized:record.providerAliasNormalized,scopeKey:record.scopeKey,canonicalTeamId:record.canonicalTeamId,status:record.status,registryVersion:record.registryVersion}}});if(!exists){await db.providerTeamAlias.create({data:record});created+=1}}
    return Object.freeze({runId:run.id,events:verified.events.length,proposals:proposals.length,created,matrix:Object.freeze(matrix)});
  }finally{await db.$disconnect()}
}

export async function approveTeamAliases(input:Readonly<{databaseUrl:string;proposalFile:string}>):Promise<Readonly<{approved:number;rejected:number;collisions:number}>>{
  if(!isAbsolute(input.proposalFile)||!input.proposalFile.endsWith(".json"))throw new Error("PROPOSAL_FILE_INVALID");const canonical=await realpath(input.proposalFile);if(canonical!==input.proposalFile)throw new Error("PROPOSAL_FILE_ALIAS_BLOCKED");const parsed=z.array(approvalSchema).safeParse(JSON.parse(await readFile(canonical,"utf8")));if(!parsed.success)throw new Error("APPROVAL_FILE_INVALID");
  const db=new PrismaClient({datasourceUrl:input.databaseUrl});let approved=0,rejected=0;try{for(const decision of parsed.data){const normalized=normalizeProviderTeamName(decision.providerAliasRaw),scope=aliasScopeKey(decision.countryScope,decision.competitionScope);const proposal=await db.providerTeamAlias.findFirst({where:{providerKey:decision.providerKey,canonicalTeamId:decision.canonicalTeamId,providerAliasNormalized:normalized,scopeKey:scope,status:"PROPOSED",sourceArtifactId:decision.sourceArtifactId,registryVersion:PROVIDER_TEAM_ALIAS_REGISTRY_VERSION},include:{canonicalTeam:true}});if(!proposal)throw new Error("APPROVAL_WITHOUT_PROPOSAL");const existing=await db.providerTeamAlias.findMany({where:{providerKey:decision.providerKey,providerAliasNormalized:normalized,scopeKey:scope,status:"APPROVED"}}) as ProviderTeamAliasRecord[];if(decision.decision==="APPROVED"&&findAliasCollision(existing,decision))throw new Error("TEAM_ALIAS_COLLISION");const record=toAliasRecord({canonicalTeamId:decision.canonicalTeamId,canonicalName:proposal.canonicalTeam.displayName,providerKey:decision.providerKey,providerAliasRaw:decision.providerAliasRaw,countryScope:decision.countryScope,competitionScope:decision.competitionScope,sourceArtifactId:decision.sourceArtifactId,evidence:{proposalId:proposal.id,decision:"EXPLICIT_REVIEW"}},decision.decision,"EXPLICIT_REVIEW_FILE");const duplicate=await db.providerTeamAlias.findUnique({where:{providerKey_providerAliasNormalized_scopeKey_canonicalTeamId_status_registryVersion:{providerKey:record.providerKey,providerAliasNormalized:record.providerAliasNormalized,scopeKey:record.scopeKey,canonicalTeamId:record.canonicalTeamId,status:record.status,registryVersion:record.registryVersion}}});if(!duplicate)await db.providerTeamAlias.create({data:record});if(decision.decision==="APPROVED")approved+=1;else rejected+=1}return Object.freeze({approved,rejected,collisions:0})}finally{await db.$disconnect()}
}
