import { mkdtemp,readFile,rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe,expect,it } from "vitest";
import { assessHistoricalCalibration,evaluateMarkets,scoreEvaluation,type DailyMarket,type DiscoveredFixture,type HistoricalCalibration } from "@/domain/market-v2/daily-analysis";
import { diagnoseOddsFixture } from "@/domain/market-v2/odds-matching";
import { classifyDailyFailure,DailyRuntimeError } from "@/infrastructure/market-v2/daily/runtime";
import { OperationalRawEvidenceStore } from "@/infrastructure/market-v2/capture/operational-evidence-store";

const fixture:DiscoveredFixture={providerFixtureId:"1",providerCompetitionId:"2",providerHomeTeamId:"3",providerAwayTeamId:"4",sportsDate:"2026-08-04",kickoffAtUtc:"2026-08-04T18:00:00.000Z",sourceTimezone:"UTC",status:"NS",season:2026,round:"1",competitionName:"Primera",country:"Paraguay",homeName:"Club Olimpia",awayName:"Cerro Porteño"};
const event=(overrides:Partial<{id:string;homeName:string;awayName:string;kickoffAtUtc:string}>={})=>({id:"e1",homeName:"Olimpia",awayName:"Cerro Porteno",kickoffAtUtc:"2026-08-04T18:05:00Z",...overrides});
const calibration=(partition:"DISCOVERY"|"VALIDATION",sampleSize:number,market:DailyMarket="HOME"):HistoricalCalibration=>({market,semanticMarket:market,partition,sampleSize,hitRate:.55,brierScore:.22,wilsonLower:.48,wilsonUpper:.62,datasetVersion:"frozen-v1"});

describe("ETAPA 19B odds, calibración y semántica",()=>{
  it("distingue respuesta vacía, match exacto, horario, nombres y ambigüedad",()=>{expect(diagnoseOddsFixture(fixture,[]).code).toBe("ODDS_EVENT_NOT_FOUND");expect(diagnoseOddsFixture(fixture,[event()])).toMatchObject({code:"USABLE_ODDS_AVAILABLE",confidence:"EXACT",matchedEventId:"e1"});expect(diagnoseOddsFixture(fixture,[event({kickoffAtUtc:"2026-08-04T19:00:00Z"})]).code).toBe("ODDS_KICKOFF_OUTSIDE_TOLERANCE");expect(diagnoseOddsFixture(fixture,[event({homeName:"Otro"})]).code).toBe("ODDS_TEAM_NAME_MISMATCH");expect(diagnoseOddsFixture(fixture,[event(),event({id:"e2"})]).code).toBe("ODDS_FIXTURE_AMBIGUOUS")});
  it("calcula 1X2, doble oportunidad y OU2.5 sin redondeo previo",()=>{const p={home:.5,draw:.3,away:.2,over25:.6,under25:.4,contextualAgreement:.8,contradictory:false,rawSignals:{}};const quotes=[{market:"HOME" as const,bookmaker:"A",odds:2.2},{market:"DRAW" as const,bookmaker:"A",odds:3.4},{market:"AWAY" as const,bookmaker:"A",odds:4.5},{market:"1X" as const,bookmaker:"A",odds:1.4},{market:"X2" as const,bookmaker:"A",odds:1.8},{market:"12" as const,bookmaker:"A",odds:1.3},{market:"OVER_25" as const,bookmaker:"A",odds:1.9},{market:"UNDER_25" as const,bookmaker:"A",odds:2.1}];const values=evaluateMarkets(p,quotes);const home=values.find((x)=>x.market==="HOME")!;expect(home.fairOdds).toBe(2);expect(home.expectedValue).toBeCloseTo(.1);expect(home.edge).toBeCloseTo(.5-(1/2.2)/(1/2.2+1/3.4+1/4.5));expect(home.marketMargin).toBeCloseTo(1/2.2+1/3.4+1/4.5-1);expect(values.find((x)=>x.market==="1X")?.status).toBe("PRICED");expect(values.find((x)=>x.market==="OVER_25")?.status).toBe("PRICED")});
  it("rechaza calibración ausente, insuficiente o semánticamente distinta",()=>{expect(assessHistoricalCalibration([],"HOME").available).toBe(false);expect(assessHistoricalCalibration([calibration("DISCOVERY",200),calibration("VALIDATION",50)],"HOME").status).toBe("INSUFFICIENT_SAMPLE");expect(assessHistoricalCalibration([calibration("DISCOVERY",200,"DRAW"),calibration("VALIDATION",200,"DRAW")],"HOME").status).toBe("MISSING_PARTITION")});
  it("acepta calibración compatible con discovery y validation",()=>expect(assessHistoricalCalibration([calibration("DISCOVERY",200),calibration("VALIDATION",150)],"HOME")).toMatchObject({available:true,status:"VALIDATED",sampleSize:150}));
  it("score parcial es mayor que cero pero queda en PASS sin histórico ni cuota",()=>{const score=scoreEvaluation({market:"HOME",probability:.68,topMargin:.2,dataQuality:1,contextualAgreement:.9,contradictory:false,historicalSample:0,edge:null,expectedValue:null,dispersion:null});expect(score.total).toBeGreaterThan(0);expect(score.total).toBeLessThan(60);expect(score.classification).toBe("PASS");expect(score.status).toBe("MODEL_ONLY")});
  it("usa errores de fase saneados y nunca UNEXPECTED_ERROR",async()=>{expect(classifyDailyFailure(new DailyRuntimeError("FIXTURE_DISCOVERY_RATE_LIMITED"))).toBe("DISCOVERY_FAILED");expect(classifyDailyFailure(new DailyRuntimeError("ODDS_MATCH_CONFLICT"))).toBe("ODDS_MATCHING_FAILED");const script=await readFile("scripts/market-v2-daily.ts","utf8");expect(script).not.toContain("UNEXPECTED_ERROR");expect(script).toContain("CORRELATION_ID")});
  it("publica evidencia raw allowlisted de The Odds API",async()=>{const root=await mkdtemp(join(tmpdir(),"market-v2-odds-evidence-"));try{const store=new OperationalRawEvidenceStore(root);await store.initialize();const result=await store.publish({providerKey:"the-odds-api",endpointKey:"odds-upcoming",capturedAtUtc:"2026-08-03T20:00:00.000Z",mediaType:"application/json",bytes:Buffer.from('{"events":[]}'),sourceReference:"daily:2026-08-04:odds"});expect(result).toMatchObject({ok:true,disposition:"CREATED"})}finally{await rm(root,{recursive:true,force:true})}});
  it("UI separa recomendaciones, observación, provisionales y descartados",async()=>{const ui=await readFile("src/components/daily-ranking-status.tsx","utf8");expect(ui).toContain("Sin recomendaciones publicables para esta fecha");expect(ui).not.toContain("Top general");for(const label of ["Recomendaciones","Observación","Candidatos provisionales","Descartados"])expect(ui).toContain(label);expect(ui).toContain("Respuesta de cuotas recibida, sin coincidencias utilizables");expect(ui).toContain('audit.classification==="SUCCESS"')});
  it("persistencia expone métricas explícitas y derivación offline",async()=>{const [schema,migration,derive]=await Promise.all([readFile("prisma/schema.prisma","utf8"),readFile("prisma/migrations/20260803213000_add_daily_odds_calibration_semantics/migration.sql","utf8"),readFile("src/infrastructure/market-v2/daily/derive-run.ts","utf8")]);for(const field of ["oddsResponseReceived","oddsEventsReceived","oddsFixturesMatched","oddsMarketsMatched","usableOddsAvailable","marketEvaluationsCreated","calibrationStatus","datasetVersion"])expect(schema).toContain(field);expect(migration).not.toMatch(/DROP|DELETE|UPDATE/);expect(derive).toContain("DERIVED_OFFLINE_NO_NETWORK");expect(derive).not.toMatch(/fetch\(|allow-network/)});
});
