import { readFile } from "node:fs/promises";
import { describe,expect,it } from "vitest";
import { evaluateMarkets } from "@/domain/market-v2/daily-analysis";
import { mapPriceableOdds } from "@/domain/market-v2/odds-market-mapping";
import { matchOddsFixtureV2,ODDS_MATCHING_V2_POLICY,type CanonicalOddsFixture,type OddsIdentityEvent } from "@/domain/market-v2/odds-matching-v2";
import { aliasScopeKey,findAliasCollision,normalizeProviderTeamName,toAliasRecord,type AliasProposal,type ProviderTeamAliasRecord,type ProviderTeamAliasStatus } from "@/domain/market-v2/provider-team-alias";
import type { OddsApiEvent } from "@/infrastructure/market-v2/the-odds-api/client";

const fixture:CanonicalOddsFixture={fixtureId:"f1",homeTeamId:"home",awayTeamId:"away",homeName:"Deportes Temuco",awayName:"Deportes Copiapó",kickoffAtUtc:"2026-08-04T00:00:00.000Z",country:"Chile",competitionName:"Primera B"};
const event=(overrides:Partial<OddsIdentityEvent>={}):OddsIdentityEvent=>({id:"e1",homeName:"Deportes Temuco",awayName:"Deportes Copiapo",kickoffAtUtc:"2026-08-04T00:05:00.000Z",sportKey:"soccer_chile_primera_b",sportTitle:"Primera B - Chile",...overrides});
const proposal=(team:"home"|"away",raw:string,scope:Partial<Pick<AliasProposal,"countryScope"|"competitionScope">>={}):AliasProposal=>({canonicalTeamId:team,canonicalName:team==="home"?fixture.homeName:fixture.awayName,providerKey:"the-odds-api",providerAliasRaw:raw,countryScope:scope.countryScope??fixture.country,competitionScope:scope.competitionScope??fixture.competitionName,sourceArtifactId:"artifact-1",evidence:{eventId:"e1",orientation:"DIRECT"}});
const alias=(team:"home"|"away",raw:string,status:ProviderTeamAliasStatus="APPROVED",scope:Partial<Pick<AliasProposal,"countryScope"|"competitionScope">>={}):ProviderTeamAliasRecord=>toAliasRecord(proposal(team,raw,scope),status,"TEST_EXPLICIT_REVIEW");

describe("odds-matching/2.0.0 con aliases aprobados",()=>{
  it("hace exact normalized direct con acentos",()=>expect(matchOddsFixtureV2(fixture,[event()],[],"artifact-1")).toMatchObject({code:"MATCHED_EXACT",confidence:"EXACT",deltaSeconds:300}));
  it("usa alias aprobado en home",()=>expect(matchOddsFixtureV2(fixture,[event({homeName:"Temuco"})],[alias("home","Temuco")],"artifact-1")).toMatchObject({code:"MATCHED_APPROVED_ALIAS",confidence:"APPROVED"}));
  it("usa alias aprobado en away",()=>expect(matchOddsFixtureV2(fixture,[event({awayName:"Copiapo"})],[alias("away","Copiapo")],"artifact-1")).toMatchObject({code:"MATCHED_APPROVED_ALIAS"}));
  it("usa aliases aprobados en ambos equipos del mismo evento",()=>{const result=matchOddsFixtureV2(fixture,[event({homeName:"Temuco",awayName:"Copiapo"})],[alias("home","Temuco"),alias("away","Copiapo")],"artifact-1");expect(result.code).toBe("MATCHED_APPROVED_ALIAS");expect(result.aliasesUsed).toHaveLength(2)});
  it.each(["PROPOSED","REJECTED"] as const)("alias %s no habilita matching",status=>expect(matchOddsFixtureV2(fixture,[event({homeName:"Temuco"})],[alias("home","Temuco",status)],"artifact-1").code).toBe("HOME_ALIAS_MISSING"));
  it("detecta colisión y ambigüedad",()=>{const first=alias("home","Temuco"),other={...alias("away","Temuco"),countryScope:first.countryScope,competitionScope:first.competitionScope,scopeKey:first.scopeKey};expect(findAliasCollision([first],other)).toBeDefined();expect(matchOddsFixtureV2(fixture,[event({homeName:"Temuco"})],[first,other],"artifact-1").code).toBe("TEAM_ALIAS_AMBIGUOUS")});
  it("rechaza scope de país incompatible",()=>expect(matchOddsFixtureV2(fixture,[event({homeName:"Temuco"})],[alias("home","Temuco","APPROVED",{countryScope:"Peru"})],"artifact-1").code).toBe("SCOPE_MISMATCH"));
  it("rechaza scope de competición incompatible",()=>expect(matchOddsFixtureV2(fixture,[event({homeName:"Temuco"})],[alias("home","Temuco","APPROVED",{competitionScope:"Copa Chile"})],"artifact-1").code).toBe("SCOPE_MISMATCH"));
  it("rechaza kickoff fuera de tolerancia",()=>expect(matchOddsFixtureV2(fixture,[event({kickoffAtUtc:"2026-08-04T01:00:00.000Z"})],[],"artifact-1").code).toBe("KICKOFF_OUTSIDE_TOLERANCE"));
  it("rechaza orientación invertida",()=>expect(matchOddsFixtureV2(fixture,[event({homeName:fixture.awayName,awayName:fixture.homeName})],[],"artifact-1").code).toBe("ORIENTATION_MISMATCH"));
  it("rechaza múltiples eventos directos",()=>expect(matchOddsFixtureV2(fixture,[event(),event({id:"e2"})],[],"artifact-1").code).toBe("MULTIPLE_EVENTS"));
  it("soporta alias regional explícito sin regla global",()=>{const regional={...fixture,homeName:"Central Cordoba de Santiago"};expect(matchOddsFixtureV2(regional,[event({homeName:"Central Cordoba SdE",awayName:regional.awayName})],[toAliasRecord({...proposal("home","Central Cordoba SdE"),canonicalName:regional.homeName},"APPROVED","TEST")],"artifact-1").code).toBe("MATCHED_APPROVED_ALIAS")});
  it("women/W requiere alias explícito",()=>{const women={...fixture,homeName:"Santos Laguna W"};expect(matchOddsFixtureV2(women,[event({homeName:"Santos Laguna Women",awayName:women.awayName})],[],"artifact-1").code).toBe("HOME_ALIAS_MISSING");expect(matchOddsFixtureV2(women,[event({homeName:"Santos Laguna Women",awayName:women.awayName})],[toAliasRecord({...proposal("home","Santos Laguna Women"),canonicalName:women.homeName},"APPROVED","TEST")],"artifact-1").code).toBe("MATCHED_APPROVED_ALIAS")});
  it("normalización conserva tokens identitarios esenciales",()=>{for(const token of ["nacional","independiente","central","universidad","atletico","deportivo","santos"])expect(normalizeProviderTeamName(token)).toBe(token);expect(normalizeProviderTeamName("Huracán FC")).toBe("huracan");expect(aliasScopeKey("Chile","Primera B")).toBe("chile|primera b")});
  it("versiona matcher y registro",()=>expect(ODDS_MATCHING_V2_POLICY).toMatchObject({version:"odds-matching/2.0.0",registryVersion:"provider-team-aliases/1.0.0",orientation:"DIRECT"}));
});

describe("mercados priceables conservadores",()=>{
  const oddsEvent:OddsApiEvent={id:"e1",commence_time:"2026-08-04T00:00:00Z",home_team:"Home",away_team:"Away",bookmakers:[{key:"a",title:"A",markets:[{key:"h2h",outcomes:[{name:"Home",price:2.2},{name:"Draw",price:3.4},{name:"Away",price:4.5}]},{key:"totals",outcomes:[{name:"Over",price:1.9,point:2.5},{name:"Under",price:2.1,point:2.5},{name:"Over",price:1.4,point:3.5}]},{key:"h2h_lay",outcomes:[{name:"Home",price:2.3}]}]}]};
  it("mapea h2h HOME DRAW AWAY",()=>expect(mapPriceableOdds(oddsEvent).matchedMarkets).toEqual(expect.arrayContaining(["HOME","DRAW","AWAY"])));
  it("mapea totals 2.5 y rechaza otro point",()=>{const mapped=mapPriceableOdds(oddsEvent);expect(mapped.matchedMarkets).toEqual(expect.arrayContaining(["OVER_25","UNDER_25"]));expect(mapped.quotes.filter(quote=>quote.market==="OVER_25")).toHaveLength(1)});
  it("ignora h2h_lay y lo registra unsupported",()=>{const mapped=mapPriceableOdds(oddsEvent);expect(mapped.unsupportedMarketKeys).toEqual(["h2h_lay"]);expect(mapped.quotes).not.toContainEqual(expect.objectContaining({odds:2.3}))});
  it("double chance ausente no genera offered odds 1X",()=>{const mapped=mapPriceableOdds(oddsEvent),evaluations=evaluateMarkets({home:.5,draw:.3,away:.2,over25:.6,under25:.4,contextualAgreement:.8,contradictory:false,rawSignals:{}},mapped.quotes);expect(mapped.doubleChanceOffered).toBe(false);const oneX=evaluations.find(value=>value.market==="1X")!;expect(oneX.fairOdds).toBeCloseTo(1/.8);expect(oneX.bestMarketOdds).toBeNull();expect(oneX.noVigProbability).toBeNull();expect(oneX.edge).toBeNull();expect(oneX.expectedValue).toBeNull()});
  it("calcula no-vig edge y EV sin redondeo",()=>{const evaluations=evaluateMarkets({home:.5,draw:.3,away:.2,over25:.6,under25:.4,contextualAgreement:.8,contradictory:false,rawSignals:{}},mapPriceableOdds(oddsEvent).quotes),home=evaluations.find(value=>value.market==="HOME")!;expect(home.noVigProbability).toBeCloseTo((1/2.2)/(1/2.2+1/3.4+1/4.5));expect(home.edge).toBeCloseTo(.5-Number(home.noVigProbability));expect(home.expectedValue).toBeCloseTo(.5*2.2-1)});
});

describe("persistencia, replay offline y UI",()=>{
  it("migración crea registro append-only y columnas de procedencia",async()=>{const migration=await readFile("prisma/migrations/20260803223000_add_provider_team_alias_registry/migration.sql","utf8");expect(migration).toContain('CREATE TABLE "ProviderTeamAlias"');expect(migration).toContain('ProviderTeamAlias_no_update');expect(migration).toContain('ProviderTeamAlias_no_delete');expect(migration).not.toMatch(/UPDATE "|DELETE FROM/u);for(const field of ["matcherVersion","aliasRegistryVersion","modelSuggestedMarket","bestPricedMarket"])expect(migration).toContain(field)});
  it("replay es append-only, conserva parent y no importa red",async()=>{const replay=await readFile("src/infrastructure/market-v2/daily/replay-odds-with-aliases.ts","utf8");expect(replay).toContain("derivedFromRunId:source.id");expect(replay).toContain("apiFootballRequests:0");expect(replay).toContain("oddsRequests:0");expect(replay).not.toMatch(/fetch\(|TheOddsApiClient|ApiFootballClient|\.update\(\{|\.delete\(\{/u)});
  it("workflow no autoaprueba similitud y exige revisión",async()=>{const workflow=await readFile("src/infrastructure/market-v2/daily/team-alias-workflow.ts","utf8");expect(workflow).toContain('"PROPOSED"');expect(workflow).toContain("EXPLICIT_REVIEW_FILE");expect(workflow).not.toMatch(/fuzzy|levenshtein|jaro/iu)});
  it("CLI no carga credenciales ni clientes HTTP",async()=>{const cli=await readFile("scripts/market-v2-team-aliases.ts","utf8");expect(cli).not.toMatch(/API_FOOTBALL_KEY|THE_ODDS_API_KEY|fetch|Client/iu);for(const action of ['action==="propose"','action==="approve"','action==="replay"'])expect(cli).toContain(action)});
  it("UI separa modelo, mercado cotizado, alias e histórico",async()=>{const ui=await readFile("src/components/daily-ranking-status.tsx","utf8");for(const text of ["Mercado sugerido por modelo","Mercado sugerido sin cotización disponible","Mercado cotizado alternativo evaluado","Fixtures exactos","Fixtures por alias","Alias aprobados","MISSING_HISTORY","Sin recomendaciones publicables para esta fecha"])expect(ui).toContain(text);expect(ui).not.toContain("Top general")});
  it("nuevos archivos no contienen secretos ni apuestas",async()=>{const files=["scripts/market-v2-team-aliases.ts","src/infrastructure/market-v2/daily/team-alias-workflow.ts","src/infrastructure/market-v2/daily/replay-odds-with-aliases.ts"];const text=(await Promise.all(files.map(file=>readFile(file,"utf8")))).join("\n");expect(text).not.toMatch(/API_FOOTBALL_KEY|THE_ODDS_API_KEY|Authorization|Cookie|stake|kelly|placeBet/iu)});
});
