import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { assertAuthorizedLegacyStatareaUrl, buildLegacyStatareaUrl, STATAREA_LEGACY_CAPTURE_POLICY_VERSION, STATAREA_LEGACY_ENDPOINT_TEMPLATE, STATAREA_LEGACY_PARSER_VERSION } from "@/domain/statarea/legacy-constants";
import { parseLegacyStatarea } from "@/domain/statarea/legacy-parser";
import { fetchLegacyStatarea, STATAREA_LEGACY_MAX_BYTES, STATAREA_LEGACY_MAX_REDIRECTS, STATAREA_LEGACY_REQUEST_HEADERS, STATAREA_LEGACY_TIMEOUT_MS } from "@/infrastructure/statarea/legacy-http-client";
import { historicalCapturePlan } from "@/application/import-history";
import { historicalDatasetContractSchema } from "@/contracts/historical-dataset";
import { reconcileIdentities } from "@/domain/reconciliation/matcher";
import { MATCH_CONFIGURATION_HASH, MATCHER_VERSION, NORMALIZER_VERSION } from "@/domain/reconciliation/configuration";

const html=readFileSync("src/tests/fixtures/statarea-legacy-small.html","utf8");const parsed=()=>parseLegacyStatarea(html,"2026-07-01");const source=(path:string)=>readFileSync(path,"utf8");
describe("Statarea Legacy oficial",()=>{
  it("distingue MODERN y LEGACY",()=>expect(new Set(["MODERN","LEGACY_OFFICIAL"]).size).toBe(2));
  it("versiona parser Legacy",()=>expect(STATAREA_LEGACY_PARSER_VERSION).toBe("statarea-legacy-daily-raw/1.0.0"));
  it("versiona política R3",()=>expect(STATAREA_LEGACY_CAPTURE_POLICY_VERSION).toBe("july-sequential-legacy-first-valid/1.1.0"));
  it("declara endpoint template exacto",()=>expect(STATAREA_LEGACY_ENDPOINT_TEMPLATE).toBe("https://old.statarea.com/predictions/YYYY-MM-DD"));
  it("construye URL exacta",()=>expect(buildLegacyStatareaUrl("2026-07-01").toString()).toBe("https://old.statarea.com/predictions/2026-07-01"));
  it.each(["http://old.statarea.com/predictions/2026-07-01","https://old2.statarea.com/predictions/2026-07-01","https://old.statarea.com/predictions/2026-07-01?x=1","https://old.statarea.com/other"])("bloquea URL arbitraria %s",(value)=>expect(()=>assertAuthorizedLegacyStatareaUrl(new URL(value))).toThrow());
  it("acepta URL legacy autorizada",()=>expect(()=>assertAuthorizedLegacyStatareaUrl(buildLegacyStatareaUrl("2026-07-21"))).not.toThrow());
  it("define límites HTTP",()=>expect([STATAREA_LEGACY_TIMEOUT_MS,STATAREA_LEGACY_MAX_BYTES,STATAREA_LEGACY_MAX_REDIRECTS]).toEqual([20000,5000000,2]));
  it("envía headers deterministas",()=>expect(STATAREA_LEGACY_REQUEST_HEADERS).toMatchObject({accept:"text/html,application/xhtml+xml","accept-language":"en-US,en;q=0.9","cache-control":"no-cache",pragma:"no-cache"}));
  it("no envía cookies",()=>expect(STATAREA_LEGACY_REQUEST_HEADERS).not.toHaveProperty("cookie"));
  it("bloquea redirect externo",async()=>{const mock=vi.fn(async()=>new Response(null,{status:302,headers:{location:"https://example.com/"}})) as unknown as typeof fetch;await expect(fetchLegacyStatarea("2026-07-01",mock)).rejects.toThrow("UNAUTHORIZED_LEGACY_URL")});
  it("bloquea tamaño declarado",async()=>{const mock=vi.fn(async()=>new Response("x",{status:200,headers:{"content-length":String(5000001)}})) as unknown as typeof fetch;await expect(fetchLegacyStatarea("2026-07-01",mock)).rejects.toThrow("RESPONSE_TOO_LARGE")});
  it("acepta respuesta local controlada",async()=>{const mock=vi.fn(async()=>new Response(html,{status:200,headers:{"content-type":"text/html"}})) as unknown as typeof fetch;expect((await fetchLegacyStatarea("2026-07-01",mock)).hostname).toBe("old.statarea.com")});
  it("acepta título correcto",()=>expect(parsed().failure).toBeNull());
  it("rechaza título de otra fecha",()=>expect(parseLegacyStatarea(html.replaceAll("2026-07-01","2026-07-02"),"2026-07-01").failure).toBe("DATE_MISMATCH"));
  it("quick nav actual no sustituye fecha",()=>expect(parsed().quickNavigationDates).toContain("2026-07-22"));
  it("filas heredan fecha solicitada",()=>expect(parsed().rows[0]).toMatchObject({rowDateRaw:"2026-07-01",requestedDate:"2026-07-01"}));
  it("rechaza fallback",()=>expect(parseLegacyStatarea(html.replace("Soccer predictions for 2026-07-01","Soccer predictions for 2026-07-22"),"2026-07-01").failure).toBe("DATE_MISMATCH"));
  it("diferencia EMPTY_VALID",()=>{const empty=html.replace(/<tr style="background:#fff">[\s\S]*?<\/tr>/,"<tr><td colspan=\"26\">There are no matches scheduled</td></tr>");expect(parseLegacyStatarea(empty,"2026-07-01").emptyValid).toBe(true)});
  it("ZERO_VALID_ROWS no es vacío válido",()=>expect(parseLegacyStatarea(html.replace(/<tr style="background:#fff">[\s\S]*?<\/tr>/,""),"2026-07-01").failure).toBe("ZERO_VALID_ROWS"));
  it("extrae país",()=>expect(parsed().rows[0]).toMatchObject({countryRaw:"Brazil"}));
  it("extrae competición",()=>expect(parsed().rows[0]).toMatchObject({competitionRaw:"Mineiro Modulo Ii Grp. A"}));
  it("extrae hora",()=>expect(parsed().rows[0]).toMatchObject({kickoffRaw:"18:00"}));
  it("extrae local",()=>expect(parsed().rows[0]).toMatchObject({homeTeamRaw:"Caldense"}));
  it("extrae visitante",()=>expect(parsed().rows[0]).toMatchObject({awayTeamRaw:"Patrocinense"}));
  it("preserva orientación",()=>expect(parsed().rows[0]).toMatchObject({orientation:"HOST_GUEST_DOM"}));
  it.each([["1","38%"],["X","32%"],["2","30%"],["H1","24%"],["HX","52%"],["H2","24%"],["1.5","67%"],["2.5","41%"],["3.5","19%"],["hc1","26%"],["hcX","38%"],["hc2","36%"]])("conserva %s raw",(header,value)=>expect((parsed().rows[0].rawColumns as Array<{headerRaw:string;valueRaw:string}>).find((column)=>column.headerRaw===header)?.valueRaw).toBe(value));
  it("tip no interpretado",()=>expect((parsed().rows[0].structuralAttributes as {tipRaw:string[]}).tipRaw).toEqual(["prdX","prd2"]));
  it("Result no aparece en fila",()=>expect(Object.keys(parsed().rows[0])).not.toContain("result"));
  it("resultado HT no aparece",()=>expect(JSON.stringify(parsed().rows[0])).not.toContain("Half time results"));
  it("cambio Result no altera sourceRowKey",()=>expect(parseLegacyStatarea(html.replace("1:2","9:9").replace("0:0","8:8"),"2026-07-01").rows[0].sourceRowKey).toBe(parsed().rows[0].sourceRowKey));
  it("cambio visual no altera sourceRowKey",()=>expect(parseLegacyStatarea(html.replace("background:#fff","background:#000"),"2026-07-01").rows[0].sourceRowKey).toBe(parsed().rows[0].sourceRowKey));
  it("2.5 conserva evidencia estructural",()=>expect((parsed().rows[0].rawColumns as Array<{headerRaw:string;semanticStatus:string}>).find((column)=>column.headerRaw==="2.5")?.semanticStatus).toBe("STRUCTURALLY_MAPPED_WITH_LABEL_EVIDENCE"));
  it("2.5 no crea señal",()=>expect(JSON.stringify(parsed())).not.toMatch(/over25Probability|under25Probability|predictedOu25Side/));
  it("planifica 21 fechas",()=>expect(historicalCapturePlan).toHaveLength(21));
  it("planifica 14 Discovery",()=>expect(historicalCapturePlan.filter((entry)=>entry.partition==="DISCOVERY")).toHaveLength(14));
  it("planifica 7 Validation",()=>expect(historicalCapturePlan.filter((entry)=>entry.partition==="VALIDATION")).toHaveLength(7));
  it("reutiliza Forebet 01",()=>expect(historicalCapturePlan[0].forebet).toBe("REUSE"));
  it("reutiliza Forebet 21",()=>expect(historicalCapturePlan[20].forebet).toBe("REUSE"));
  it("captura Forebet 02-20",()=>expect(historicalCapturePlan.slice(1,20).every((entry)=>entry.forebet==="CAPTURE")).toBe(true));
  it("captura Legacy 01-21",()=>expect(historicalCapturePlan.every((entry)=>entry.statarea==="LEGACY_CAPTURE")).toBe(true));
  it("no fija Statarea moderno 21",()=>expect(source("src/application/import-history.ts")).not.toContain("PINNED_STATAREA"));
  it("crea run histórico 21",()=>expect(source("src/application/import-history.ts")).not.toContain("b5c18db1-c81a-483c-be12-786ae160c0cd"));
  it("matcher conserva versión",()=>expect(MATCHER_VERSION).toBe("ou25-fixture-matcher/1.0.0"));
  it("normalizador conserva versión",()=>expect(NORMALIZER_VERSION).toBe("ou25-identity-normalizer/1.0.0"));
  it("configurationHash conserva valor",()=>expect(MATCH_CONFIGURATION_HASH).toBe("b659064ddf02ce1c14bb30f40db4dd3609258f51e7639e380ac020ab2787e90b"));
  it("aliases siguen cero",()=>expect(source("src/domain/reconciliation/configuration.ts")).toMatch(/aliases:\s*\[\]/));
  it("columnas predictivas no entran al matcher",()=>expect(source("src/domain/reconciliation/matcher.ts")).not.toMatch(/rawColumns|Result|Tips|averageGoals/));
  it("matching ignora extras",()=>{const a=[{id:"f",homeTeamRaw:"A",awayTeamRaw:"B",competitionRaw:"L",countryRaw:"C",categoryRaw:null,result:"1:0"}];const b=[{id:"s",homeTeamRaw:"A",awayTeamRaw:"B",competitionRaw:"L",countryRaw:"C",categoryRaw:null,"2.5":"99%"}];const clean=[{id:"f",homeTeamRaw:"A",awayTeamRaw:"B",competitionRaw:"L",countryRaw:"C",categoryRaw:null}];const cleanB=[{id:"s",homeTeamRaw:"A",awayTeamRaw:"B",competitionRaw:"L",countryRaw:"C",categoryRaw:null}];expect(reconcileIdentities(a,b).decisions).toEqual(reconcileIdentities(clean,cleanB).decisions)});
  it("modelo define relación uno-a-uno",()=>expect(source("prisma/schema.prisma")).toMatch(/snapshotId\s+String\s+@unique/));
  it("perfiles son append-only",()=>expect(source("prisma/migrations/20260722172000_add_statarea_snapshot_profiles/migration.sql")).toContain("StatareaSnapshotProfile_no_update"));
  it("días son append-only",()=>expect(source("prisma/migrations/20260722152456_add_frozen_july_historical_dataset/migration.sql")).toContain("HistoricalDatasetDay_no_update"));
  it("auditoría es append-only",()=>expect(source("prisma/migrations/20260722152456_add_frozen_july_historical_dataset/migration.sql")).toContain("HistoricalAuditEvent_no_delete"));
  it("tarea sucesora registra presentación",()=>expect(source("src/application/import-history.ts")).toContain('sourcePresentation:"LEGACY_OFFICIAL"'));
  it("dataset sigue V1",()=>expect(source("src/domain/history/constants.ts")).toContain('HISTORY_VERSION = "1.0.0"'));
  it("contrato bloquea MODERN",()=>{const fixture=JSON.parse(source("src/contracts/fixtures/historical-dataset.valid.json"));fixture.days[0].sourceSnapshots.statarea.sourcePresentation="MODERN";expect(historicalDatasetContractSchema.safeParse(fixture).success).toBe(false)});
  it.each(["result","hitRate","Score","ranking","odds","recommendation"])("contrato bloquea %s",(field)=>{const fixture=JSON.parse(source("src/contracts/fixtures/historical-dataset.valid.json"));fixture.days[0][field]=1;expect(historicalDatasetContractSchema.safeParse(fixture).success).toBe(false)});
  it("manifiesto usa JSON canónico",()=>expect(source("src/infrastructure/history/export-store.ts")).toContain("canonicalJson"));
  it("replay retorna cero red",()=>expect(source("src/application/import-history.ts")).toMatch(/networkRequestCount:0/));
  it("día completo no se recaptura",()=>expect(source("src/application/import-history.ts")).toContain("datasetId_sportsDate"));
  it("exports quedan fuera de Git",()=>expect(source(".gitignore")).toContain("/var/exports/"));
  it("UI identifica Legacy",()=>expect(source("src/components/historical-dataset-status.tsx")).toContain("Legacy oficial"));
  it("UI separa evidencia moderna",()=>expect(source("src/components/historical-dataset-status.tsx")).toContain("fuera del dataset histórico"));
  it("UI mantiene acciones deshabilitadas",()=>expect(source("src/components/historical-dataset-status.tsx")).toContain("disabled"));
  it("UI no muestra Result",()=>expect(source("src/components/historical-dataset-status.tsx")).not.toContain("day.result"));
  it("no usa Apostala",()=>expect(source("src/application/import-history.ts")).not.toMatch(/Apostala/i));
  it("no depende de x2-ht-lab",()=>expect(source("src/application/import-history.ts")).not.toMatch(/x2-ht-lab/i));
  it("preserva B002-B004",()=>expect(source("src/domain/reconciliation/configuration.ts")).toContain("ou25-fixture-matcher/1.0.0"));
});
