import {readFileSync} from "node:fs";import {describe,expect,it,vi} from "vitest";import {assertAuthorizedStatareaUrl,buildStatareaUrl,validateStatareaDate} from "@/domain/statarea/constants";import {fetchStatarea,STATAREA_MAX_BYTES,STATAREA_MAX_REDIRECTS,STATAREA_TIMEOUT_MS} from "@/infrastructure/statarea/http-client";import {canonicalJson} from "@/domain/canonical-json";import {snapshotDecision,appendAudit} from "@/domain/forebet/capture-policy";
describe("seguridad Statarea",()=>{
 it("construye la URL autorizada",()=>expect(buildStatareaUrl("2026-07-21").toString()).toBe("https://www.statarea.com/predictions/date/2026-07-21/competition"));
 it("rechaza URL y dominio arbitrarios",()=>{expect(()=>assertAuthorizedStatareaUrl(new URL("https://example.com/predictions/date/2026-07-21/competition"))).toThrow("UNAUTHORIZED_URL");expect(()=>assertAuthorizedStatareaUrl(new URL("https://www.statarea.com/other"))).toThrow("UNAUTHORIZED_URL")});
 it("valida fecha y rechaza variantes",()=>{expect(validateStatareaDate("2026-07-21")).toBe("2026-07-21");for(const value of ["21-07-2026","2026-02-30","2026-07-20"])expect(()=>validateStatareaDate(value)).toThrow()});
 it("define timeout, tamaño y redirects limitados",()=>{expect(STATAREA_TIMEOUT_MS).toBe(20000);expect(STATAREA_MAX_BYTES).toBe(5000000);expect(STATAREA_MAX_REDIRECTS).toBe(2)});
 it("rechaza HTTP y tamaño excesivo de forma detectable",async()=>{const http=vi.fn(async()=>new Response("x",{status:403,headers:{"content-type":"text/html"}})) as unknown as typeof fetch;expect((await fetchStatarea("2026-07-21",http)).httpStatus).toBe(403);const large=vi.fn(async()=>new Response("x",{status:200,headers:{"content-length":String(STATAREA_MAX_BYTES+1)}})) as unknown as typeof fetch;await expect(fetchStatarea("2026-07-21",large)).rejects.toThrow("RESPONSE_TOO_LARGE")});
 it("permite redirect interno exacto y bloquea externo",async()=>{let calls=0;const internal=vi.fn(async()=>{calls++;return calls===1?new Response(null,{status:302,headers:{location:"/predictions/date/2026-07-21/competition"}}):new Response("ok",{status:200,headers:{"content-type":"text/html"}})}) as unknown as typeof fetch;expect((await fetchStatarea("2026-07-21",internal)).httpStatus).toBe(200);const external=vi.fn(async()=>new Response(null,{status:302,headers:{location:"https://example.com/x"}})) as unknown as typeof fetch;await expect(fetchStatarea("2026-07-21",external)).rejects.toThrow("UNAUTHORIZED_URL")});
 it("modela idempotencia, nuevo hash, inmutabilidad y auditoría",()=>{const old=Object.freeze(["a"]);expect(snapshotDecision(old,"a")).toBe("REUSE");expect(snapshotDecision(old,"b")).toBe("CREATE");expect(old).toEqual(["a"]);expect(appendAudit(old,"b")).toEqual(["a","b"])});
 it("JSON canónico es reproducible",()=>expect(canonicalJson({b:2,a:1})).toBe(canonicalJson({a:1,b:2})));
 it("el export contractual no contiene resultados",()=>{const value=readFileSync("src/contracts/fixtures/statarea-daily-capture.valid.json","utf8");expect(value).not.toMatch(/homeGoals|awayGoals|finalScore|halfTimeScore|\"result\"/i)});
 it("la migración bloquea UPDATE y DELETE append-only",()=>{const sql=readFileSync("prisma/migrations/20260722135900_enforce_statarea_append_only/migration.sql","utf8");for(const table of ["StatareaCaptureSnapshot","StatareaRawRow","StatareaRowRejection","StatareaCaptureAuditEvent"]){expect(sql).toContain(`BEFORE UPDATE ON \"${table}\"`);expect(sql).toContain(`BEFORE DELETE ON \"${table}\"`)}});
 it("el servicio Statarea no modifica modelos Forebet",()=>{const value=readFileSync("src/application/capture-statarea.ts","utf8");expect(value).not.toMatch(/forebetCaptureSnapshot|forebetObservation|forebetRowRejection|forebetCaptureAttempt/)});
 it("no usa fuentes o dependencias fuera de alcance",()=>{for(const path of ["src/application/capture-statarea.ts","src/infrastructure/statarea/http-client.ts","package.json","prisma/schema.prisma"]){const value=readFileSync(path,"utf8");expect(value).not.toMatch(/apostala|x2-ht-lab/i)}});
 it("UI no expone señal ni habilita ranking",()=>{const value=readFileSync("src/app/page.tsx","utf8");expect(value).not.toMatch(/statareaOu25Signal|over25Probability|under25Probability/);expect(value).toMatch(/disabled/)});
});
