import { createHash } from "node:crypto";
import { normalizeName } from "./daily-analysis";

export const PROVIDER_TEAM_ALIAS_REGISTRY_VERSION="provider-team-aliases/1.0.0" as const;
export type ProviderTeamAliasStatus="PROPOSED"|"APPROVED"|"REJECTED";
export type ProviderTeamAliasRecord=Readonly<{id:string;providerKey:string;canonicalTeamId:string;providerAliasRaw:string;providerAliasNormalized:string;canonicalNameAtApproval:string;countryScope:string|null;competitionScope:string|null;scopeKey:string;status:ProviderTeamAliasStatus;approvalMethod:string;sourceArtifactId:string;evidenceJson:string;registryVersion:string}>;
export type AliasProposal=Readonly<{canonicalTeamId:string;canonicalName:string;providerKey:"the-odds-api";providerAliasRaw:string;countryScope:string|null;competitionScope:string|null;sourceArtifactId:string;evidence:Readonly<Record<string,unknown>>}>;

export function normalizeProviderTeamName(value:string):string{return normalizeName(value)}
export function aliasScopeKey(countryScope:string|null,competitionScope:string|null):string{return `${countryScope?normalizeProviderTeamName(countryScope):"*"}|${competitionScope?normalizeProviderTeamName(competitionScope):"*"}`}
export function aliasDecisionId(input:Readonly<{providerKey:string;canonicalTeamId:string;providerAliasRaw:string;countryScope:string|null;competitionScope:string|null;status:ProviderTeamAliasStatus;sourceArtifactId:string}>):string{return `alias-${createHash("sha256").update([PROVIDER_TEAM_ALIAS_REGISTRY_VERSION,input.providerKey,input.canonicalTeamId,normalizeProviderTeamName(input.providerAliasRaw),aliasScopeKey(input.countryScope,input.competitionScope),input.status,input.sourceArtifactId].join("\0")).digest("hex").slice(0,32)}`}
export function scopeCompatible(alias:Pick<ProviderTeamAliasRecord,"countryScope"|"competitionScope">,fixture:Readonly<{country:string;competitionName:string}>):boolean{return (!alias.countryScope||normalizeProviderTeamName(alias.countryScope)===normalizeProviderTeamName(fixture.country))&&(!alias.competitionScope||normalizeProviderTeamName(alias.competitionScope)===normalizeProviderTeamName(fixture.competitionName))}
export function findAliasCollision(existing:readonly ProviderTeamAliasRecord[],candidate:Readonly<{providerKey:string;canonicalTeamId:string;providerAliasRaw:string;countryScope:string|null;competitionScope:string|null}>):ProviderTeamAliasRecord|undefined{const normalized=normalizeProviderTeamName(candidate.providerAliasRaw),scope=aliasScopeKey(candidate.countryScope,candidate.competitionScope);return existing.find(alias=>alias.status==="APPROVED"&&alias.providerKey===candidate.providerKey&&alias.providerAliasNormalized===normalized&&alias.scopeKey===scope&&alias.canonicalTeamId!==candidate.canonicalTeamId)}
export function toAliasRecord(proposal:AliasProposal,status:ProviderTeamAliasStatus,approvalMethod:string):ProviderTeamAliasRecord{const base={providerKey:proposal.providerKey,canonicalTeamId:proposal.canonicalTeamId,providerAliasRaw:proposal.providerAliasRaw,countryScope:proposal.countryScope,competitionScope:proposal.competitionScope,status,sourceArtifactId:proposal.sourceArtifactId};return Object.freeze({id:aliasDecisionId(base),...base,providerAliasNormalized:normalizeProviderTeamName(proposal.providerAliasRaw),canonicalNameAtApproval:proposal.canonicalName,scopeKey:aliasScopeKey(proposal.countryScope,proposal.competitionScope),approvalMethod,evidenceJson:JSON.stringify(proposal.evidence),registryVersion:PROVIDER_TEAM_ALIAS_REGISTRY_VERSION})}
