import { database } from "@/infrastructure/database";
import { DAILY_LOCALE, DAILY_TIME_ZONE } from "@/domain/market-v2/daily-analysis";

const dateTime = new Intl.DateTimeFormat(DAILY_LOCALE, { timeZone: DAILY_TIME_ZONE, dateStyle: "medium", timeStyle: "short" });
const percent = (value: unknown) => value === null || value === undefined ? "—" : `${(Number(value) * 100).toLocaleString(DAILY_LOCALE, { maximumFractionDigits: 1 })} %`;
const decimal = (value: unknown) => value === null || value === undefined ? "Cuota no disponible" : Number(value).toLocaleString(DAILY_LOCALE, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const list = (value: string) => { try { const parsed = JSON.parse(value) as unknown; return Array.isArray(parsed) ? parsed.map(String) : []; } catch { return []; } };

export async function DailyRankingStatus() {
  const run = await database.dailyAnalysisRun.findFirst({ orderBy: [{ completedAtUtc: "desc" }, { id: "desc" }], include: { exclusions: { orderBy: { createdAtUtc: "asc" } }, candidates: { include: { fixture: { include: { homeTeam: true, awayTeam: true } }, recommendations: { include: { marketEvaluation: true }, orderBy: { rank: "asc" } } } } } });
  if (!run) return <section className="panel empty-state"><span className="eyebrow">Ranking diario D+1</span><h1>Mejores partidos</h1><p>Aún no existe una ejecución publicada. La vista es de solo lectura y nunca ejecuta apuestas.</p></section>;
  const recommendations = run.candidates.flatMap((candidate) => candidate.recommendations.map((recommendation) => ({ candidate, recommendation }))).sort((a,b)=>a.recommendation.rank-b.recommendation.rank);
  const byMarket = [...new Map(recommendations.map((entry) => [entry.recommendation.market, entry])).values()];
  const warnings = list(run.warningsJson);
  return <>
    <section className="daily-hero"><div><span className="eyebrow">Evaluación D+1 · decisión manual</span><h1>Mejores partidos</h1><p className="subtitle">Fecha deportiva {run.sportsDate} · zona horaria {DAILY_TIME_ZONE}</p></div><div className="daily-mode"><strong>{run.mode === "FULL" ? "FULL" : "PROVISIONAL"}</strong><small>Última ejecución · {dateTime.format(run.completedAtUtc)}</small></div></section>
    <section className="metric-grid daily-metrics">{[["Descubiertos",run.fixturesDiscovered],["Elegibles",run.fixturesEligible],["Analizados",run.fixturesDeepAnalyzed],["Descartados",run.fixturesExcluded],["Ranking",run.recommendations]].map(([label,value])=><article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>
    {warnings.length>0&&<section className="panel daily-warning"><span className="eyebrow">Advertencias metodológicas</span><ul>{warnings.map((warning)=><li key={warning}>{warning.replaceAll("_"," ")}</li>)}</ul><p>No existe calibración histórica apta para promover este resultado a FULL. Ninguna fila representa certeza ni apuesta garantizada.</p></section>}
    <section><div className="section-heading"><div><span className="eyebrow">Top general</span><h2>Ranking explicable</h2></div><span className="date">Revisión inicial · PENDING_REVIEW</span></div><div className="daily-list">{recommendations.map(({candidate,recommendation})=>{const evaluation=recommendation.marketEvaluation;return <article className="daily-card" key={recommendation.id}><div className="daily-rank">#{recommendation.rank}</div><div className="daily-match"><span>{candidate.fixture.country} · {candidate.fixture.competitionName}</span><h2>{candidate.fixture.homeTeam.displayName} <i>vs.</i> {candidate.fixture.awayTeam.displayName}</h2><small>{dateTime.format(candidate.fixture.kickoffAtUtc)}</small></div><div className="daily-market"><span>Mercado sugerido</span><strong>{recommendation.market}</strong><small>{recommendation.recommendationStatus}</small></div><dl className="daily-numbers"><div><dt>Modelo</dt><dd>{percent(evaluation.modelProbability)}</dd></div><div><dt>Cuota justa</dt><dd>{decimal(evaluation.fairOdds)}</dd></div><div><dt>Mejor cuota</dt><dd>{decimal(evaluation.bestMarketOdds)}</dd></div><div><dt>Mercado sin margen</dt><dd>{percent(evaluation.noVigProbability)}</dd></div><div><dt>Edge</dt><dd>{percent(evaluation.edge)}</dd></div><div><dt>EV</dt><dd>{percent(evaluation.expectedValue)}</dd></div></dl><div className="daily-score"><strong>{Number(recommendation.scoreTotal).toFixed(1)}</strong><span>{recommendation.classification}</span><small>{recommendation.reviewStatus}</small></div><div className="daily-detail"><p><b>Muestra histórica:</b> {evaluation.historicalSample}</p><p><b>Razones:</b> {list(recommendation.explanationJson).join(" · ") || "Evaluación provisional"}</p><p><b>Riesgos:</b> {list(recommendation.risksJson).join(" · ") || "Sin riesgos adicionales registrados"}</p></div></article>})}</div></section>
    <section className="panel daily-market-top"><span className="eyebrow">Top por mercado</span><div>{byMarket.map(({candidate,recommendation})=><p key={recommendation.market}><strong>{recommendation.market}</strong> · #{recommendation.rank} {candidate.fixture.homeTeam.displayName} — {candidate.fixture.awayTeam.displayName} · {Number(recommendation.scoreTotal).toFixed(1)}</p>)}</div></section>
    <section className="panel"><span className="eyebrow">Metodología</span><h2>Política daily-ranking/1.0.0</h2><p>Score de 100 puntos: confianza del modelo 25, calibración histórica 25, valor de mercado 25, acuerdo contextual 15 y calidad de datos 10. Empates, muestras insuficientes, señales contradictorias, cuotas ausentes y dispersión alta aplican penalizaciones versionadas.</p></section>
    <details className="panel daily-exclusions"><summary>Descartados ({run.exclusions.length})</summary>{run.exclusions.map((exclusion)=><p key={exclusion.id}><strong>{exclusion.fixtureLabel}</strong> · {exclusion.reasonCode.replaceAll("_"," ")}</p>)}</details>
  </>;
}
