import { database } from "@/infrastructure/database";
import { DAILY_LOCALE, DAILY_TIME_ZONE } from "@/domain/market-v2/daily-analysis";

const dateTime=new Intl.DateTimeFormat(DAILY_LOCALE,{timeZone:DAILY_TIME_ZONE,dateStyle:"medium",timeStyle:"short"});
const percent=(value:unknown)=>value===null||value===undefined?"—":`${(Number(value)*100).toLocaleString(DAILY_LOCALE,{maximumFractionDigits:1})} %`;
const decimal=(value:unknown)=>value===null||value===undefined?"Cuota no disponible":Number(value).toLocaleString(DAILY_LOCALE,{minimumFractionDigits:2,maximumFractionDigits:2});
const list=(value:string)=>{try{const parsed:unknown=JSON.parse(value);return Array.isArray(parsed)?parsed.map(String):[]}catch{return[]}};

export async function DailyRankingStatus(){
  const run=await database.dailyAnalysisRun.findFirst({orderBy:[{completedAtUtc:"desc"},{id:"desc"}],include:{requestAudits:true,exclusions:{orderBy:{createdAtUtc:"asc"}},candidates:{include:{fixture:{include:{homeTeam:true,awayTeam:true}},recommendations:{include:{marketEvaluation:true},orderBy:{rank:"asc"}}}}}});
  if(!run)return <section className="panel empty-state"><span className="eyebrow">Ranking diario D+1</span><h1>Mejores partidos</h1><p>Aún no existe una ejecución publicada. La vista es de solo lectura y nunca ejecuta apuestas.</p></section>;
  const entries=run.candidates.flatMap((candidate)=>candidate.recommendations.map((recommendation)=>({candidate,recommendation}))).sort((a,b)=>a.recommendation.rank-b.recommendation.rank);
  const publishable=entries.filter(({recommendation})=>recommendation.classification==="STRONG"||recommendation.classification==="INTERESTING");
  const watch=entries.filter(({recommendation})=>recommendation.classification==="WATCH");
  const provisional=entries.filter(({recommendation})=>recommendation.recommendationStatus.includes("MODEL_ONLY"));
  const discarded=entries.filter(({recommendation})=>recommendation.classification==="PASS"&&!recommendation.recommendationStatus.includes("MODEL_ONLY"));
  const oddsRequestSucceeded=run.requestAudits.some((audit)=>audit.providerId==="provider-the-odds-api"&&audit.endpointKey==="odds-upcoming"&&audit.classification==="SUCCESS");
  const oddsMessage=run.usableOddsAvailable?"Cuotas utilizables disponibles":run.oddsResponseReceived&&oddsRequestSucceeded?"Respuesta de cuotas recibida, sin coincidencias utilizables":"Proveedor de cuotas no disponible";
  const cards=(values:typeof entries,showRank:boolean)=>values.map(({candidate,recommendation})=>{const evaluation=recommendation.marketEvaluation;return <article className="daily-card" key={recommendation.id}>{showRank&&<div className="daily-rank">#{recommendation.rank}</div>}<div className="daily-match"><span>{candidate.fixture.country} · {candidate.fixture.competitionName}</span><h2>{candidate.fixture.homeTeam.displayName} <i>vs.</i> {candidate.fixture.awayTeam.displayName}</h2><small>{dateTime.format(candidate.fixture.kickoffAtUtc)}</small></div><div className="daily-market"><span>Mercado evaluado</span><strong>{recommendation.market}</strong><small>{recommendation.recommendationStatus}</small></div><dl className="daily-numbers"><div><dt>Modelo</dt><dd>{percent(evaluation.modelProbability)}</dd></div><div><dt>Cuota justa</dt><dd>{decimal(evaluation.fairOdds)}</dd></div><div><dt>Mejor cuota</dt><dd>{decimal(evaluation.bestMarketOdds)}</dd></div><div><dt>Mercado sin margen</dt><dd>{percent(evaluation.noVigProbability)}</dd></div><div><dt>Edge</dt><dd>{percent(evaluation.edge)}</dd></div><div><dt>EV</dt><dd>{percent(evaluation.expectedValue)}</dd></div></dl><div className="daily-score"><strong>{Number(recommendation.scoreTotal).toFixed(1)}</strong><span>{recommendation.classification}</span><small>{recommendation.reviewStatus}</small></div><div className="daily-detail"><p><b>Muestra histórica:</b> {evaluation.historicalSample} · {evaluation.calibrationStatus}</p><p><b>Razones:</b> {list(recommendation.explanationJson).join(" · ")}</p><p><b>Riesgos:</b> {list(recommendation.risksJson).join(" · ")}</p></div></article>});
  return <>
    <section className="daily-hero"><div><span className="eyebrow">Evaluación D+1 · decisión manual</span><h1>Mejores partidos</h1><p className="subtitle">Fecha deportiva {run.sportsDate} · zona horaria {DAILY_TIME_ZONE}</p></div><div className="daily-mode"><strong>{run.mode==="FULL"?"FULL":"PROVISIONAL"}</strong><small>Última ejecución · {dateTime.format(run.completedAtUtc)}</small></div></section>
    <section className="metric-grid daily-metrics">{[["Descubiertos",run.fixturesDiscovered],["Analizados",run.fixturesDeepAnalyzed],["Eventos odds",run.oddsEventsReceived],["Fixtures odds",run.oddsFixturesMatched],["Mercados evaluados",run.marketEvaluationsCreated]].map(([label,value])=><article className="metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className="panel daily-warning"><span className="eyebrow">Disponibilidad de cuotas</span><h2>{oddsMessage}</h2><p>Respuesta: {run.oddsResponseReceived?"sí":"no"} · eventos: {run.oddsEventsReceived} · fixtures vinculados: {run.oddsFixturesMatched} · mercados vinculados: {run.oddsMarketsMatched} · cuotas utilizables: {run.usableOddsAvailable?"sí":"no"}.</p></section>
    {publishable.length===0&&<section className="panel daily-warning"><span className="eyebrow">Recomendaciones</span><h2>Sin recomendaciones publicables para esta fecha</h2><p>Faltan las capas históricas y/o de precio necesarias. No se presenta ningún candidato como apuesta ni como superioridad estadística validada.</p></section>}
    {publishable.length>0&&<section><div className="section-heading"><div><span className="eyebrow">Recomendaciones</span><h2>STRONG e INTERESTING</h2></div></div><div className="daily-list">{cards(publishable,true)}</div></section>}
    {watch.length>0&&<section><div className="section-heading"><div><span className="eyebrow">Observación</span><h2>WATCH</h2></div></div><div className="daily-list">{cards(watch,false)}</div></section>}
    <section><div className="section-heading"><div><span className="eyebrow">Información parcial</span><h2>Candidatos provisionales</h2></div><span className="date">{provisional.length} · PENDING_REVIEW</span></div><div className="daily-list">{cards(provisional,false)}</div></section>
    <section className="panel"><span className="eyebrow">Metodología</span><h2>Política daily-ranking/1.1.0</h2><p>Modelo, acuerdo contextual y calidad pueden puntuar sin histórico ni cuotas. Las capas ausentes puntúan cero, aplican penalización y un techo provisional. STRONG e INTERESTING exigen histórico suficiente, cuota utilizable, edge mínimo, EV positivo y calidad suficiente.</p></section>
    <details className="panel daily-exclusions"><summary>Descartados ({discarded.length+run.exclusions.length})</summary>{discarded.map(({candidate,recommendation})=><p key={recommendation.id}><strong>{candidate.fixture.homeTeam.displayName} — {candidate.fixture.awayTeam.displayName}</strong> · PASS</p>)}{run.exclusions.map((exclusion)=><p key={exclusion.id}><strong>{exclusion.fixtureLabel}</strong> · {exclusion.reasonCode.replaceAll("_"," ")}</p>)}</details>
  </>;
}
