import { database } from "@/infrastructure/database";

const formatter = new Intl.DateTimeFormat("es-PY", { timeZone: "America/Asuncion", dateStyle: "medium", timeStyle: "medium" });
export async function ReconciliationStatus() {
  const run = await database.matchRun.findFirst({ where: { runType: "PRIMARY" }, orderBy: { createdAt: "desc" }, include: { decisions: { where: { status: { in: ["MATCHED", "AMBIGUOUS", "CONFLICT"] } }, take: 30, orderBy: [{ status: "asc" }, { id: "asc" }] } } });
  if (!run) return <section className="panel"><span className="eyebrow">Conciliación de fuentes</span><h2>Sin run de matching</h2><p>Ejecute el comando local controlado. No se realizará acceso de red.</p></section>;
  const forebetIds = run.decisions.flatMap((decision) => decision.forebetObservationId ? [decision.forebetObservationId] : []); const statareaIds = run.decisions.flatMap((decision) => decision.statareaRowId ? [decision.statareaRowId] : []);
  const [forebet, statarea] = await Promise.all([database.forebetObservation.findMany({ where: { id: { in: forebetIds } }, select: { id: true, homeTeamRaw: true, awayTeamRaw: true, competitionRaw: true } }), database.statareaRawRow.findMany({ where: { id: { in: statareaIds } }, select: { id: true, homeTeamRaw: true, awayTeamRaw: true, competitionRaw: true } })]); const f = new Map(forebet.map((row) => [row.id, row])); const s = new Map(statarea.map((row) => [row.id, row]));
  const coverage = (matched: number, total: number) => total ? `${((matched / total) * 100).toFixed(1)}%` : "0.0%";
  return <section className="panel"><span className="eyebrow">Conciliación de fuentes</span><div className="section-heading"><h2>{run.status}</h2><span className="date">{formatter.format(run.createdAt)}</span></div><dl><div><dt>Fecha</dt><dd>{run.sportDate.toISOString().slice(0,10)}</dd></div><div><dt>Snapshots</dt><dd>{run.forebetSnapshotId.slice(0,12)} / {run.statareaSnapshotId.slice(0,12)}</dd></div><div><dt>Matcher / normalizador</dt><dd>{run.matcherVersion} / {run.normalizerVersion}</dd></div><div><dt>MATCHED</dt><dd>{run.matchedCount}</dd></div><div><dt>AMBIGUOUS</dt><dd>{run.ambiguousCount}</dd></div><div><dt>ONLY_FOREBET</dt><dd>{run.onlyForebetCount}</dd></div><div><dt>ONLY_STATAREA</dt><dd>{run.onlyStatareaCount}</dd></div><div><dt>CONFLICT</dt><dd>{run.conflictCount}</dd></div><div><dt>Cobertura Forebet</dt><dd>{coverage(run.matchedCount,run.forebetInputCount)}</dd></div><div><dt>Cobertura Statarea</dt><dd>{coverage(run.matchedCount,run.statareaInputCount)}</dd></div></dl><p>La fuente Statarea presentó variación de contenido entre capturas de la misma fecha. La conciliación está fijada a snapshots específicos.</p><h3>Revisión de identidad</h3><div role="table" aria-label="Decisiones de conciliación">{run.decisions.map((decision)=>{const left=f.get(decision.forebetObservationId ?? "");const right=s.get(decision.statareaRowId ?? "");return <p key={decision.id}><strong>{decision.status}</strong> · {left ? `${left.homeTeamRaw}–${left.awayTeamRaw}` : "—"} ↔ {right ? `${right.homeTeamRaw}–${right.awayTeamRaw}` : "—"} · {decision.reasonCode}</p>})}</div><p>No se muestran predicciones, resultados, consenso ni ranking.</p></section>;
}
