import { z } from "zod";

const sha = z.string().regex(/^[a-f0-9]{64}$/);
const snapshot = z.object({ id: z.string().min(1), sha256: sha, rowCount: z.number().int().nonnegative() }).strict();
const candidate = z.object({ id: z.string(), forebetObservationId: z.string(), statareaRowId: z.string(), orientation: z.enum(["DIRECT", "REVERSED"]), homeScore: z.number().min(0).max(1), awayScore: z.number().min(0).max(1), aggregateScore: z.number().min(0).max(1), marginToSecond: z.number().nullable(), stage: z.enum(["EXACT", "CONSERVATIVE", "APPROXIMATE", "CONFLICT"]), rank: z.number().int().positive(), evidence: z.record(z.string(), z.unknown()), rejectionReasons: z.array(z.string()) }).strict();
const decision = z.object({ id: z.string(), status: z.enum(["MATCHED", "AMBIGUOUS", "ONLY_FOREBET", "ONLY_STATAREA", "CONFLICT"]), forebetObservationId: z.string().nullable(), statareaRowId: z.string().nullable(), selectedCandidateId: z.string().nullable(), reasonCode: z.string().min(1).max(100), reasons: z.array(z.string()), warnings: z.array(z.string()), confidenceClass: z.enum(["EXACT", "STRONG", "REVIEW", "UNRESOLVED"]), identity: z.object({ forebet: z.object({ homeRaw: z.string().nullable(), awayRaw: z.string().nullable(), competitionRaw: z.string().nullable(), countryRaw: z.string().nullable(), homeNormalized: z.string().nullable(), awayNormalized: z.string().nullable() }).strict(), statarea: z.object({ homeRaw: z.string().nullable(), awayRaw: z.string().nullable(), competitionRaw: z.string().nullable(), countryRaw: z.string().nullable(), homeNormalized: z.string().nullable(), awayNormalized: z.string().nullable() }).strict() }).strict() }).strict().superRefine((value, context) => {
  if (value.status === "MATCHED" && (!value.forebetObservationId || !value.statareaRowId || !value.selectedCandidateId)) context.addIssue({ code: "custom", message: "MATCHED exige ambos IDs y candidato" });
  if (value.status === "ONLY_FOREBET" && (!value.forebetObservationId || value.statareaRowId)) context.addIssue({ code: "custom", message: "ONLY_FOREBET inválido" });
  if (value.status === "ONLY_STATAREA" && (!value.statareaRowId || value.forebetObservationId)) context.addIssue({ code: "custom", message: "ONLY_STATAREA inválido" });
  if (value.status === "CONFLICT" && !value.reasonCode) context.addIssue({ code: "custom", message: "CONFLICT exige razón" });
});
const counts = z.object({ forebetInput: z.number().int().nonnegative(), statareaInput: z.number().int().nonnegative(), matched: z.number().int().nonnegative(), ambiguous: z.number().int().nonnegative(), onlyForebet: z.number().int().nonnegative(), onlyStatarea: z.number().int().nonnegative(), conflict: z.number().int().nonnegative(), exact: z.number().int().nonnegative(), conservative: z.number().int().nonnegative(), approximate: z.number().int().nonnegative() }).strict();
const stability = z.object({ presentInAllSnapshots: z.number().int().nonnegative(), presentInOneOrTwo: z.number().int().nonnegative(), commonMatches: z.number().int().nonnegative(), primaryOnlyMatches: z.number().int().nonnegative(), coverageByRun: z.array(z.object({ runId: z.string(), forebet: z.number(), statarea: z.number() }).strict()), changedStates: z.number().int().nonnegative(), newConflicts: z.number().int().nonnegative(), newAmbiguous: z.number().int().nonnegative() }).strict();

export const reconciliationContractSchema = z.object({ contractVersion: z.literal("1.0"), matchRun: z.object({ id: z.string(), sportDate: z.iso.date(), runType: z.enum(["PRIMARY", "STABILITY_DIAGNOSTIC"]), status: z.literal("COMPLETED"), matcherVersion: z.string(), normalizerVersion: z.string(), configurationHash: sha, createdAt: z.iso.datetime() }).strict(), sourceSnapshots: z.object({ forebet: snapshot, statarea: snapshot }).strict(), configuration: z.object({ code: z.literal("OU25-MATCHER"), status: z.literal("DRAFT"), hash: sha, value: z.record(z.string(), z.unknown()) }).strict(), counts, coverage: z.object({ forebet: z.number().min(0).max(1), statarea: z.number().min(0).max(1) }).strict(), decisions: z.array(decision), candidates: z.array(candidate), stabilityDiagnostic: stability.nullable(), warnings: z.array(z.string()), generatedAt: z.iso.datetime() }).strict().superRefine((value, context) => {
  const forebet = new Set<string>(); const statarea = new Set<string>();
  for (const [index, decision] of value.decisions.entries()) if (decision.status === "MATCHED") {
    if (forebet.has(decision.forebetObservationId!)) context.addIssue({ code: "custom", path: ["decisions", index], message: "Forebet duplicado" });
    if (statarea.has(decision.statareaRowId!)) context.addIssue({ code: "custom", path: ["decisions", index], message: "Statarea duplicado" });
    forebet.add(decision.forebetObservationId!); statarea.add(decision.statareaRowId!);
  }
});
export type ReconciliationContract = z.infer<typeof reconciliationContractSchema>;
