import { canonicalHash } from "@/domain/canonical-hash";
import {
  HISTORICAL_DATASET_CODE,
  HISTORICAL_DATASET_ID,
  HISTORICAL_DATASET_VERSION,
  HISTORICAL_MANIFEST_HASH,
  HISTORICAL_REGISTRY_HASH,
} from "@/domain/historical-analysis/constants";
import {
  HISTORICAL_ANALYSIS_SPEC_HASH,
  MARKET_PRIORITY_ASSESSMENT_MODE,
  MARKET_PRIORITY_DEVELOPMENT_WINDOW,
  MARKET_PRIORITY_ENGINE_VERSION,
  MARKET_PRIORITY_INDEPENDENT_VALIDATION_STATUS,
  MARKET_PRIORITY_POLICY_CODE,
  MARKET_PRIORITY_POLICY_STATUS,
  MARKET_PRIORITY_POLICY_VERSION,
} from "./constants";

export const marketPriorityPolicy = {
  code: MARKET_PRIORITY_POLICY_CODE,
  version: MARKET_PRIORITY_POLICY_VERSION,
  status: MARKET_PRIORITY_POLICY_STATUS,
  engineVersion: MARKET_PRIORITY_ENGINE_VERSION,
  frozenReferences: {
    datasetId: HISTORICAL_DATASET_ID,
    datasetCode: HISTORICAL_DATASET_CODE,
    datasetVersion: HISTORICAL_DATASET_VERSION,
    manifestHash: HISTORICAL_MANIFEST_HASH,
    semanticRegistryHash: HISTORICAL_REGISTRY_HASH,
    historicalAnalysisSpecHash: HISTORICAL_ANALYSIS_SPEC_HASH,
  },
  evidenceBoundary: {
    developmentEvidenceWindow: MARKET_PRIORITY_DEVELOPMENT_WINDOW,
    independentValidationStatus: MARKET_PRIORITY_INDEPENDENT_VALIDATION_STATUS,
    prospectiveValidationRequired: true,
    assessmentMode: MARKET_PRIORITY_ASSESSMENT_MODE,
    outcomeEvaluationEnabled: false,
    allowedEvidence: "FROZEN_AGGREGATE_PATTERN_EVALUATION_ONLY",
    prohibitedIndividualEvidence: [
      "FixtureOutcome",
      "OutcomeEvidence",
      "INDIVIDUAL_HIT_MISS",
      "ACTUAL_TOTAL_GOALS",
      "ACTUAL_RESULT_1X2",
      "INDIVIDUAL_SCORE",
    ],
  },
  families: {
    doubleChance: {
      alternatives: ["1X", "X2", "12"],
      familyWinner: "HIGHEST_FINAL_PRIORITY_SCORE_WITH_STRICT_TIE_BREAK",
      tieBreak: ["historicalEvidenceScore", "dataQualityScore", "signalScore", "validationWilsonLower", "validationN"],
      unresolvedTie: "FAMILY_TIE_NO_AUTOMATIC_WINNER",
    },
    ou25: {
      creation: "FOREBET_EXPLICIT_SIDE_EQUALS_STATAREA_GT_OR_LT_50",
      statareaNoSignal: "SOURCE_OVER_25_PERCENT_EQUALS_50",
      historicalPattern: "OU25_CONSENSUS_SIMPLE",
      strengthLabels: ["SIMPLE", "MODERATE_60", "STRONG_65", "EXTREME_70"],
      thresholdSelection: "DESCRIPTIVE_ONLY_NOT_RETROSPECTIVELY_OPTIMIZED",
      confluenceBonus: 0,
      confluenceWarning: "FOREBET_CONFLUENCE_VALIDATION_DROP",
    },
    sameMatchCombination: {
      creation: "DOUBLE_CHANCE_FAMILY_WINNER_AND_OU25_CANDIDATE_REQUIRED",
      lineFormat: "<DC> + <OU>",
      exactHistoricalPattern: "COMBO_<DC>_<OU>",
      jointProbabilityCalculated: false,
      sourcePercentAggregation: "PROHIBITED",
    },
  },
  formulas: {
    decimalLibrary: "decimal.js",
    roundingDecimalPlaces: 6,
    doubleChanceSignal: {
      percentComponent: "30*clamp((p-50)/40,0,1)",
      lineMargin: "p-secondHighestDcPercent",
      marginComponent: "10*clamp(lineMargin/20,0,1)",
      signalScore: "percentComponent+marginComponent",
    },
    ou25Signal: {
      minimumAgreementPercent: "min(forebetSidePercent,statareaSidePercent)",
      strengthComponent: "32*clamp((minimumAgreementPercent-50)/25,0,1)",
      sourceGap: "abs(forebetSidePercent-statareaSidePercent)",
      balanceComponent: "8*(1-clamp(sourceGap/20,0,1))",
      signalScore: "strengthComponent+balanceComponent",
    },
    combinationSignal: "min(dcSignalScore,ouSignalScore)",
    historicalEvidence: {
      validationHitRateComponent: "12*validationHitRate",
      validationWilsonLowerComponent: "12*validationWilsonLower",
      sampleComponent: { "0..9": 0, "10..29": 4, "30+": 8 },
      stabilityComponent: { STABLE_OR_IMPROVED: 8, MODERATE_DROP: 4, SEVERE_DROP: 0 },
      discoverySubstitution: false,
    },
    dataQuality: {
      matching: { EXACT: 8, CONSERVATIVE: 6, APPROXIMATE: 3 },
      completeRequiredFields: 6,
      semanticReady: 4,
      snapshotIntegrityVerified: 2,
    },
    priority: "signalScore+historicalEvidenceScore+dataQualityScore",
  },
  caps: {
    historicalEvidence: [
      { when: "validationN=0", maximum: 0 },
      { when: "validationN<10", maximum: 20 },
      { when: "10<=validationN<30", maximum: 28 },
      { when: "stabilityClass=SEVERE_DROP", maximum: 18 },
      { when: "stabilityClass=MODERATE_DROP", maximum: 30 },
    ],
    priority: [
      { when: "dataQualityScore<14", maximum: 64 },
      { when: "validationN<10", maximum: 64 },
      { when: "stabilityClass=SEVERE_DROP", maximum: 64 },
      { when: "stabilityClass=MODERATE_DROP", maximum: 74 },
      { when: "maxCountryShare>0.50 OR maxCompetitionShare>0.40", maximum: 84 },
      { when: "family=OU25 AND validationLift<=0", maximum: 84 },
    ],
  },
  blockers: [
    "MISSING_REQUIRED_SOURCE_FIELD",
    "SEMANTICALLY_NOT_READY",
    "MATCH_NOT_ELIGIBLE",
    "SNAPSHOT_INTEGRITY_FAILURE",
    "POLICY_REFERENCE_MISMATCH",
    "HISTORICAL_METRIC_NOT_FOUND",
  ],
  classes: [
    { code: "HIGH", minimum: 85, maximum: 100 },
    { code: "INTERESTING", minimum: 75, maximum: 84.999999 },
    { code: "TRACK", minimum: 65, maximum: 74.999999 },
    { code: "DO_NOT_PRIORITIZE", minimum: 0, maximum: 64.999999 },
  ],
  finalSelection: {
    alternativesMaximum: 3,
    tieBreak: ["finalPriorityScore", "historicalEvidenceScore", "dataQualityScore", "signalScore", "validationWilsonLower", "validationN"],
    unresolvedTie: "FINAL_TIE",
    preferred: { minimumScore: 75, minimumMarginToSecond: 5, blockersAllowed: false },
    provisional: { minimumScore: 65 },
    none: "NO_ELIGIBLE_CANDIDATE_AT_OR_ABOVE_65_OR_FINAL_TIE",
    selectedLineMaximum: 1,
  },
  priceBoundary: {
    priceStatus: "NOT_EVALUATED",
    availableOdds: null,
    marketValueStatus: "UNKNOWN",
    breakEvenComparisonStatus: "NOT_AVAILABLE",
    mandatoryWarning: "PRICE_REQUIRED_BEFORE_REAL_USE",
  },
  warnings: [
    "PRICE_REQUIRED_BEFORE_REAL_USE",
    "FOREBET_CONFLUENCE_VALIDATION_DROP",
    "INDEPENDENT_VALIDATION_NOT_AVAILABLE",
    "PROSPECTIVE_VALIDATION_REQUIRED",
  ],
  prohibitedOutputs: [
    "SELECTION_HIT_RATE",
    "SELECTION_WILSON",
    "SELECTION_BRIER",
    "PROFIT",
    "STAKE",
    "DAILY_RANKING",
    "MULTI_MATCH_COMBINATION",
    "RECOMMENDATION",
    "JOINT_PROBABILITY",
  ],
} as const;

export const marketPriorityPolicyHash = canonicalHash(marketPriorityPolicy);
