"""Deterministic, unmistakably synthetic R0 packet fixtures."""

import hashlib
from typing import Any

from ou25_analytics.prospective.contracts import packet_payload_hash


def _hash(label: str) -> str:
    return hashlib.sha256(label.encode("utf-8")).hexdigest()


def make_synthetic_packet_payload() -> dict[str, Any]:
    """Build one deterministic full-lifecycle packet without real sports data."""

    captured = {
        "fixture-a": "2030-02-01T10:00:00.000Z",
        "fixture-b": "2030-02-01T10:00:00.000Z",
        "forebet-a": "2030-02-01T12:00:00.000Z",
        "forebet-b": "2030-02-01T13:00:00.000Z",
        "odds-a": "2030-02-01T16:50:00.000Z",
        "odds-b": "2030-02-01T18:45:00.000Z",
        "closing-a": "2030-02-01T17:55:00.000Z",
        "outcome-a": "2030-02-01T22:00:00.000Z",
        "outcome-b": "2030-02-02T00:00:00.000Z",
    }
    artifacts = {
        label: {
            "artifact_reference": f"synth:evidence:{label}",
            "source_name": "SYNTHETIC_SOURCE",
            "captured_at_utc": timestamp,
            "content_hash": _hash(label),
        }
        for label, timestamp in captured.items()
    }
    payload: dict[str, Any] = {
        "protocol_version": "prospective-r0/1.0",
        "packet_id": "SYNTH_PACKET_R0_001",
        "generated_at_utc": "2030-02-02T01:00:00.000Z",
        "source_metadata": {
            "synthetic": True,
            "capture_stage": "SYNTHETIC_FULL",
            "source_names": ["SYNTHETIC_FIXTURE_SOURCE", "SYNTHETIC_FOREBET", "SYNTH_BOOK_A"],
            "data_classification": "SYNTHETIC",
        },
        "capture_universe": {
            "protocol_version": "prospective-r0/1.0",
            "phase": "PILOT",
            "competition_allowlist": ["SYNTH_COMP_ALPHA"],
            "date_from": "2030-02-01",
            "date_to": "2030-02-01",
            "required_markets": ["MATCH_ODDS_1X2", "DOUBLE_CHANCE", "DRAW_NO_BET"],
            "allowed_bookmakers": ["SYNTH_BOOK_A"],
            "snapshot_schedule": [
                {
                    "role": "EARLY",
                    "target_seconds_before_kickoff": 21600,
                    "tolerance_seconds": 1800,
                },
                {
                    "role": "DECISION",
                    "target_seconds_before_kickoff": 3600,
                    "tolerance_seconds": 900,
                },
                {"role": "CLOSING", "target_seconds_before_kickoff": 300, "tolerance_seconds": 180},
            ],
            "postponed_fixture_policy": "RECAPTURE_NEW_KICKOFF",
            "unreliable_kickoff_policy": "BLOCK_DECISION",
        },
        "fixtures": [
            {
                "source_fixture_id": "SYNTH_FIXTURE_A",
                "source_name": "SYNTHETIC_FIXTURE_SOURCE",
                "competition_raw": "Synthetic Competition Alpha",
                "competition_key": "SYNTH_COMP_ALPHA",
                "home_team_raw": "Synthetic Home A",
                "away_team_raw": "Synthetic Away A",
                "home_team_id": "SYNTH_TEAM_HOME_A",
                "away_team_id": "SYNTH_TEAM_AWAY_A",
                "kickoff_raw": "2030-02-01 18:00 UTC",
                "kickoff_source_timezone": "UTC",
                "kickoff_at_utc": "2030-02-01T18:00:00.000Z",
                "kickoff_confidence": "CONFIRMED",
                "fixture_status": "SCHEDULED",
                "captured_at_utc": captured["fixture-a"],
                "source_artifact_reference": artifacts["fixture-a"]["artifact_reference"],
                "content_hash": artifacts["fixture-a"]["content_hash"],
            },
            {
                "source_fixture_id": "SYNTH_FIXTURE_B",
                "source_name": "SYNTHETIC_FIXTURE_SOURCE",
                "competition_raw": "Synthetic Competition Alpha",
                "competition_key": "SYNTH_COMP_ALPHA",
                "home_team_raw": "Synthetic Home B",
                "away_team_raw": "Synthetic Away B",
                "home_team_id": "SYNTH_TEAM_HOME_B",
                "away_team_id": "SYNTH_TEAM_AWAY_B",
                "kickoff_raw": "2030-02-01 20:00 UTC",
                "kickoff_source_timezone": "UTC",
                "kickoff_at_utc": "2030-02-01T20:00:00.000Z",
                "kickoff_confidence": "HIGH",
                "fixture_status": "SCHEDULED",
                "captured_at_utc": captured["fixture-b"],
                "source_artifact_reference": artifacts["fixture-b"]["artifact_reference"],
                "content_hash": artifacts["fixture-b"]["content_hash"],
            },
        ],
        "forebet_snapshots": [
            {
                "forebet_snapshot_id": "SYNTH_FOREBET_A",
                "source_fixture_id": "SYNTH_FIXTURE_A",
                "captured_at_utc": captured["forebet-a"],
                "home_probability": 0.55,
                "draw_probability": 0.25,
                "away_probability": 0.20,
                "predicted_home_score": 2,
                "predicted_away_score": 1,
                "source_page_reference": "synth:page:forebet-a",
                "source_artifact_reference": artifacts["forebet-a"]["artifact_reference"],
                "parser_version": "synthetic-parser/1.0",
                "content_hash": artifacts["forebet-a"]["content_hash"],
            },
            {
                "forebet_snapshot_id": "SYNTH_FOREBET_B",
                "source_fixture_id": "SYNTH_FIXTURE_B",
                "captured_at_utc": captured["forebet-b"],
                "home_probability": 0.65,
                "draw_probability": 0.20,
                "away_probability": 0.15,
                "predicted_home_score": 1,
                "predicted_away_score": 0,
                "source_page_reference": "synth:page:forebet-b",
                "source_artifact_reference": artifacts["forebet-b"]["artifact_reference"],
                "parser_version": "synthetic-parser/1.0",
                "content_hash": artifacts["forebet-b"]["content_hash"],
            },
        ],
        "odds_snapshots": [
            {
                "odds_snapshot_id": "SYNTH_ODDS_A_1X",
                "source_fixture_id": "SYNTH_FIXTURE_A",
                "bookmaker_key": "SYNTH_BOOK_A",
                "market_key": "DOUBLE_CHANCE",
                "selection_key": "HOME_OR_DRAW",
                "captured_at_utc": captured["odds-a"],
                "decimal_odds": 1.60,
                "raw_odds": "1.60",
                "line_value": None,
                "market_status": "ACTIVE",
                "is_in_play": False,
                "source_event_id": "SYNTH_EVENT_A",
                "source_market_id": "SYNTH_MARKET_A_DC",
                "source_selection_id": "SYNTH_SELECTION_A_1X",
                "source_artifact_reference": artifacts["odds-a"]["artifact_reference"],
                "price_kind": "OFFERED",
                "content_hash": artifacts["odds-a"]["content_hash"],
            },
            {
                "odds_snapshot_id": "SYNTH_ODDS_B_AWAY",
                "source_fixture_id": "SYNTH_FIXTURE_B",
                "bookmaker_key": "SYNTH_BOOK_A",
                "market_key": "MATCH_ODDS_1X2",
                "selection_key": "AWAY",
                "captured_at_utc": captured["odds-b"],
                "decimal_odds": 2.20,
                "raw_odds": "2.20",
                "line_value": None,
                "market_status": "ACTIVE",
                "is_in_play": False,
                "source_event_id": "SYNTH_EVENT_B",
                "source_market_id": "SYNTH_MARKET_B_1X2",
                "source_selection_id": "SYNTH_SELECTION_B_AWAY",
                "source_artifact_reference": artifacts["odds-b"]["artifact_reference"],
                "price_kind": "OFFERED",
                "content_hash": artifacts["odds-b"]["content_hash"],
            },
        ],
        "decisions": [
            {
                "decision_id": "SYNTH_DECISION_A",
                "fixture_id": "SYNTH_FIXTURE_A",
                "decided_at_utc": "2030-02-01T17:00:00.000Z",
                "decision_status": "SELECTED",
                "reason_code": "SYNTH_CONCORDANT_CASE",
                "selected_market_key": "DOUBLE_CHANCE",
                "selected_selection_key": "HOME_OR_DRAW",
                "selected_odds_snapshot_id": "SYNTH_ODDS_A_1X",
                "estimated_probability": 0.80,
                "break_even_probability": 0.625,
                "estimated_edge": 0.175,
                "policy_version": "synthetic-policy/1.0",
                "input_hash": _hash("decision-a-inputs"),
            },
            {
                "decision_id": "SYNTH_DECISION_B",
                "fixture_id": "SYNTH_FIXTURE_B",
                "decided_at_utc": "2030-02-01T19:00:00.000Z",
                "decision_status": "ABSTAINED",
                "reason_code": "SYNTH_DIVERGENCE_REQUIRES_ABSTENTION",
                "selected_market_key": None,
                "selected_selection_key": None,
                "selected_odds_snapshot_id": None,
                "estimated_probability": 0.15,
                "break_even_probability": None,
                "estimated_edge": None,
                "policy_version": "synthetic-policy/1.0",
                "input_hash": _hash("decision-b-inputs"),
            },
        ],
        "closing_snapshots": [
            {
                "closing_snapshot_id": "SYNTH_CLOSING_A_1X",
                "fixture_id": "SYNTH_FIXTURE_A",
                "bookmaker_key": "SYNTH_BOOK_A",
                "market_key": "DOUBLE_CHANCE",
                "selection_key": "HOME_OR_DRAW",
                "captured_at_utc": captured["closing-a"],
                "decimal_odds": 1.55,
                "seconds_before_kickoff": 300,
                "status": "ACTIVE",
                "source_artifact_reference": artifacts["closing-a"]["artifact_reference"],
                "content_hash": artifacts["closing-a"]["content_hash"],
            }
        ],
        "outcomes": [
            {
                "outcome_id": "SYNTH_OUTCOME_A_V1",
                "fixture_id": "SYNTH_FIXTURE_A",
                "observed_at_utc": captured["outcome-a"],
                "source_name": "SYNTHETIC_OUTCOME_SOURCE",
                "home_score": 2,
                "away_score": 1,
                "result_1x2": "HOME",
                "outcome_status": "FINAL",
                "supersedes_outcome_id": None,
                "source_artifact_reference": artifacts["outcome-a"]["artifact_reference"],
                "content_hash": artifacts["outcome-a"]["content_hash"],
            },
            {
                "outcome_id": "SYNTH_OUTCOME_B_V1",
                "fixture_id": "SYNTH_FIXTURE_B",
                "observed_at_utc": captured["outcome-b"],
                "source_name": "SYNTHETIC_OUTCOME_SOURCE",
                "home_score": 0,
                "away_score": 0,
                "result_1x2": "DRAW",
                "outcome_status": "FINAL",
                "supersedes_outcome_id": None,
                "source_artifact_reference": artifacts["outcome-b"]["artifact_reference"],
                "content_hash": artifacts["outcome-b"]["content_hash"],
            },
        ],
        "evidence_manifest": {"items": list(artifacts.values())},
    }
    payload["packet_hash"] = packet_payload_hash(payload)
    return payload
