import { randomUUID } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { canonicalHash } from "@/domain/canonical-hash";
import { statareaLegacyCaptureContractSchema, type StatareaLegacyCaptureContract } from "@/contracts/statarea-legacy-capture";
import { STATAREA_SOURCE, validateStatareaDate } from "@/domain/statarea/constants";
import { assertAuthorizedLegacyStatareaUrl, buildLegacyStatareaUrl, STATAREA_LEGACY_CAPTURE_POLICY_VERSION, STATAREA_LEGACY_ENDPOINT_TEMPLATE, STATAREA_LEGACY_PARSER_VERSION, STATAREA_LEGACY_SOURCE_PRESENTATION } from "@/domain/statarea/legacy-constants";
import { parseLegacyStatarea } from "@/domain/statarea/legacy-parser";
import { preserveSourceEvidence } from "@/infrastructure/forebet/evidence-store";
import { fetchLegacyStatarea, type LegacyStatareaHttpResponse } from "@/infrastructure/statarea/legacy-http-client";
import { preserveLegacyStatareaExport } from "@/infrastructure/statarea/legacy-export-store";

type Dependencies = { prisma: PrismaClient; fetcher?: (date:string)=>Promise<LegacyStatareaHttpResponse> };
const dv=(date:string)=>new Date(`${date}T00:00:00.000Z`); const j=(value:unknown)=>JSON.stringify(value);

export async function captureLegacyStatarea(date:string,{prisma,fetcher=fetchLegacyStatarea}:Dependencies):Promise<StatareaLegacyCaptureContract>{
  validateStatareaDate(date);const requestedUrl=buildLegacyStatareaUrl(date).toString();
  await prisma.statareaCaptureAuditEvent.create({data:{eventType:"LEGACY_CAPTURE_STARTED",requestedDate:dv(date),detailsJson:j({source:STATAREA_SOURCE,sourcePresentation:STATAREA_LEGACY_SOURCE_PRESENTATION,date,endpoint:requestedUrl,parserVersion:STATAREA_LEGACY_PARSER_VERSION})}});
  let response:LegacyStatareaHttpResponse;
  try{response=await fetcher(date)}catch(error){const code=error instanceof Error?error.message:"CAPTURE_ERROR";await prisma.$transaction([prisma.statareaCaptureAttempt.create({data:{requestedDate:dv(date),requestedUrl,capturedAt:new Date(),parserVersion:STATAREA_LEGACY_PARSER_VERSION,status:"FAILED",errorCode:code}}),prisma.statareaCaptureAuditEvent.create({data:{eventType:"LEGACY_CAPTURE_FAILED",requestedDate:dv(date),detailsJson:j({source:STATAREA_SOURCE,sourcePresentation:STATAREA_LEGACY_SOURCE_PRESENTATION,date,error:code})}})]);throw error}
  assertAuthorizedLegacyStatareaUrl(new URL(response.finalUrl));const evidence=await preserveSourceEvidence("statarea-legacy",date,response.body);const base={requestedDate:dv(date),requestedUrl:response.requestedUrl,finalUrl:response.finalUrl,hostname:response.hostname,capturedAt:response.capturedAt,httpStatus:response.httpStatus,contentType:response.contentType,byteSize:response.body.byteLength,contentHash:evidence.hash,parserVersion:STATAREA_LEGACY_PARSER_VERSION};
  const html=response.body.toString("utf8");const transportFailure=response.httpStatus!==200?`HTTP_${response.httpStatus}`:!response.contentType.toLowerCase().includes("text/html")?"INVALID_CONTENT_TYPE":!response.body.length?"EMPTY_CONTENT":/captcha|cf-chl-|access denied|verify you are human/i.test(html)?"BLOCKED_CONTENT":null;
  const parsed=transportFailure?null:parseLegacyStatarea(html,date);const failure=transportFailure??parsed?.failure??null;
  if(failure){await prisma.$transaction([prisma.statareaCaptureAttempt.create({data:{...base,status:"FAILED",errorCode:failure}}),prisma.statareaCaptureAuditEvent.create({data:{eventType:"LEGACY_CAPTURE_FAILED",requestedDate:dv(date),detailsJson:j({source:STATAREA_SOURCE,sourcePresentation:STATAREA_LEGACY_SOURCE_PRESENTATION,date,hash:evidence.hash,error:failure})}})]);throw new Error(failure)}
  const valid=parsed!;const existing=await prisma.statareaCaptureSnapshot.findUnique({where:{requestedDate_contentHash_parserVersion:{requestedDate:dv(date),contentHash:evidence.hash,parserVersion:STATAREA_LEGACY_PARSER_VERSION}},include:{profile:true}});if(existing?.profile?.sourcePresentation&&existing.profile.sourcePresentation!==STATAREA_LEGACY_SOURCE_PRESENTATION)throw new Error("SOURCE_PRESENTATION_COLLISION");
  const snapshotId=existing?.id??randomUUID();const exportPath=`var/exports/statarea-legacy/${date}/${snapshotId}.json`;const status: "SUCCEEDED"|"PARTIAL"|"REUSED"=existing?"REUSED":valid.rejections.length?"PARTIAL":"SUCCEEDED";const warningCount=valid.warnings.length;
  const contract:StatareaLegacyCaptureContract={contractVersion:"1.0",source:STATAREA_SOURCE,sourcePresentation:STATAREA_LEGACY_SOURCE_PRESENTATION,requestedDate:date,captureAttempt:{status,requestedUrl:response.requestedUrl,finalUrl:response.finalUrl,hostname:response.hostname,httpStatus:200,contentType:response.contentType,capturedAt:response.capturedAt.toISOString(),byteSize:response.body.byteLength},snapshot:{id:snapshotId,contentHash:evidence.hash,evidencePath:evidence.relativePath,exportPath},parserVersion:STATAREA_LEGACY_PARSER_VERSION,counts:{rowsFound:valid.rowsFound,valid:valid.rows.length,rejected:valid.rejections.length,duplicates:valid.duplicateRows,warnings:warningCount,unverifiedColumns:5},rows:valid.rows.map((row)=>{const value=row as Record<string,unknown>;return{sourceRowKey:value.sourceRowKey as string,rowDateRaw:value.rowDateRaw as string,kickoffRaw:value.kickoffRaw as string,competitionRaw:value.competitionRaw as string,countryRaw:value.countryRaw as string,categoryRaw:null,homeTeamRaw:value.homeTeamRaw as string,awayTeamRaw:value.awayTeamRaw as string,orientation:"HOST_GUEST_DOM",rawColumns:value.rawColumns as never,semanticStatus:"STRUCTURALLY_MAPPED",warnings:value.warnings as string[]}}),rejectedRows:valid.rejections.map((row)=>({rowIndex:row.rowIndex,reasonCode:row.reasonCode})),rawHeaders:valid.rawHeaders,semanticRegistry:valid.semanticRegistry as StatareaLegacyCaptureContract["semanticRegistry"],warnings:valid.warnings,qualityStatus:valid.emptyValid?"EMPTY_VALID":valid.rejections.length?"PARTIAL":"CONTROLLED",resultsPersisted:false,statarea25SemanticStatus:"STRUCTURALLY_MAPPED_WITH_LABEL_EVIDENCE"};
  statareaLegacyCaptureContractSchema.parse(contract);canonicalHash(contract);
  if(!existing){await preserveLegacyStatareaExport(date,snapshotId,contract);await prisma.statareaCaptureSnapshot.create({data:{id:snapshotId,requestedDate:dv(date),contentHash:evidence.hash,parserVersion:STATAREA_LEGACY_PARSER_VERSION,evidencePath:evidence.relativePath,exportPath,rawHeadersJson:j(valid.rawHeaders),semanticRegistryJson:j(valid.semanticRegistry),rowsFound:valid.rowsFound,validRows:valid.rows.length,rejectedRows:valid.rejections.length,duplicateRows:valid.duplicateRows,warningCount,profile:{create:{id:randomUUID(),sourcePresentation:STATAREA_LEGACY_SOURCE_PRESENTATION,endpointTemplate:STATAREA_LEGACY_ENDPOINT_TEMPLATE,requestedUrl:response.requestedUrl,finalUrl:response.finalUrl,parserVersion:STATAREA_LEGACY_PARSER_VERSION,capturePolicyVersion:STATAREA_LEGACY_CAPTURE_POLICY_VERSION}},rows:{create:valid.rows.map((rowValue)=>{const row=rowValue as Record<string,unknown>;return{source:"STATAREA" as const,requestedDate:dv(date),rowDateRaw:row.rowDateRaw as string,kickoffRaw:row.kickoffRaw as string,competitionRaw:row.competitionRaw as string,countryRaw:row.countryRaw as string,categoryRaw:null,homeTeamRaw:row.homeTeamRaw as string,awayTeamRaw:row.awayTeamRaw as string,orientation:"HOST_GUEST_DOM",rowTextRaw:row.rowTextRaw as string,rawColumnsJson:j(row.rawColumns),structuralAttributesJson:j(row.structuralAttributes),sourceRowKey:row.sourceRowKey as string,parserVersion:STATAREA_LEGACY_PARSER_VERSION,parseStatus:"VALID" as const,semanticStatus:"STRUCTURALLY_MAPPED" as const,warningsJson:j(row.warnings)}})},rejections:{create:valid.rejections.map((row)=>({rowIndex:row.rowIndex,sourceRowKey:row.sourceRowKey,reasonCode:row.reasonCode,detailsJson:j(row.details)}))}}});}
  await prisma.$transaction([prisma.statareaCaptureAttempt.create({data:{...base,status,snapshotId,warning:valid.warnings.join("; ")||null}}),prisma.statareaCaptureAuditEvent.create({data:{eventType:existing?"LEGACY_SNAPSHOT_REUSED":"LEGACY_SNAPSHOT_CREATED",requestedDate:dv(date),snapshotId,detailsJson:j({source:STATAREA_SOURCE,sourcePresentation:STATAREA_LEGACY_SOURCE_PRESENTATION,date,hash:evidence.hash,parserVersion:STATAREA_LEGACY_PARSER_VERSION,counts:contract.counts,resultsPersisted:false})}})]);
  return contract;
}
