import { randomUUID } from "node:crypto";
import type { ForebetCaptureSnapshot, PrismaClient, StatareaCaptureSnapshot, StatareaSnapshotProfile } from "@prisma/client";
import { captureForebetOu25 } from "@/application/capture-forebet";
import { captureLegacyStatarea } from "@/application/capture-statarea-legacy";
import { ensureLegacyRecoveryPolicy, ensureModernStatareaProfiles } from "@/application/statarea-profiles";
import { canonicalHash } from "@/domain/canonical-hash";
import { buildHistoricalManifest } from "@/domain/history/manifest";
import { CAPTURE_MINIMUM_PAUSE_MS, CAPTURE_POLICY_VERSION, DISCOVERY_TO, HISTORY_CODE, HISTORY_FROM, HISTORY_TO, HISTORY_VERSION, PINNED_FOREBET_01_HASH, PINNED_FOREBET_HASH, PINNED_FOREBET_ID, VALIDATION_FROM, historyDates, historyPartition, validateHistoryRange } from "@/domain/history/constants";
import { MATCH_CONFIGURATION, MATCH_CONFIGURATION_HASH, MATCHER_VERSION, NORMALIZER_VERSION } from "@/domain/reconciliation/configuration";
import { reconcileIdentities } from "@/domain/reconciliation/matcher";
import { STATAREA_LEGACY_ENDPOINT_TEMPLATE, STATAREA_LEGACY_PARSER_VERSION } from "@/domain/statarea/legacy-constants";
import { database } from "@/infrastructure/database";
import { preserveHistoryExports } from "@/infrastructure/history/export-store";

const dv=(date:string)=>new Date(`${date}T00:00:00.000Z`);const wait=(ms:number)=>new Promise((resolve)=>setTimeout(resolve,ms));
const identitySelect={id:true,homeTeamRaw:true,awayTeamRaw:true,competitionRaw:true,countryRaw:true,categoryRaw:true} as const;
const retryable=(error:unknown)=>error instanceof Error&&(/abort|timeout|HTTP_5\d\d|fetch failed|ECONNRESET|ETIMEDOUT/i.test(error.message));
type LegacySnapshot=StatareaCaptureSnapshot&{profile:StatareaSnapshotProfile};

export const historicalCapturePlan=historyDates().map((date)=>({date,partition:historyPartition(date),forebet:date==="2026-07-01"||date==="2026-07-21"?"REUSE":"CAPTURE",statarea:"LEGACY_CAPTURE" as const}));

async function audit(prisma:PrismaClient,datasetId:string,importRunId:string|null,eventType:string,details:Record<string,unknown>,sportsDate?:string,source?:"FOREBET"|"STATAREA"){await prisma.historicalAuditEvent.create({data:{datasetId,importRunId,eventType,sportsDate:sportsDate?dv(sportsDate):null,source,detailsJson:JSON.stringify({datasetId,sportsDate:sportsDate??null,partition:sportsDate?historyPartition(sportsDate):null,source:source??null,...details})}})}

async function findForebet(prisma:PrismaClient,date:string){if(date===HISTORY_TO){const snapshot=await prisma.forebetCaptureSnapshot.findUnique({where:{id:PINNED_FOREBET_ID}});if(snapshot?.contentHash!==PINNED_FOREBET_HASH)throw new Error("PINNED_FOREBET_2026_07_21_MISMATCH");return snapshot}const attempt=await prisma.forebetCaptureAttempt.findFirst({where:{requestedDate:dv(date),status:{in:["SUCCEEDED","PARTIAL"]},snapshotId:{not:null}},orderBy:{capturedAt:"asc"},include:{snapshot:true}});const snapshot=attempt?.snapshot??null;if(date===HISTORY_FROM&&snapshot?.contentHash!==PINNED_FOREBET_01_HASH)throw new Error("PINNED_FOREBET_2026_07_01_MISMATCH");return snapshot}
async function findLegacy(prisma:PrismaClient,date:string):Promise<LegacySnapshot|null>{const profile=await prisma.statareaSnapshotProfile.findFirst({where:{sourcePresentation:"LEGACY_OFFICIAL",parserVersion:STATAREA_LEGACY_PARSER_VERSION,snapshot:{requestedDate:dv(date)}},include:{snapshot:true},orderBy:{createdAt:"asc"}});return profile?{...profile.snapshot,profile}:null}

export async function createHistoricalMatchRun(prisma:PrismaClient,datasetId:string,date:string,forebet:ForebetCaptureSnapshot,statarea:StatareaCaptureSnapshot){
  const unique={sportDate:dv(date),forebetSnapshotId:forebet.id,statareaSnapshotId:statarea.id,matcherVersion:MATCHER_VERSION,normalizerVersion:NORMALIZER_VERSION,configurationHash:MATCH_CONFIGURATION_HASH,runType:"HISTORICAL_DATASET" as const};const existing=await prisma.matchRun.findUnique({where:{sportDate_forebetSnapshotId_statareaSnapshotId_matcherVersion_normalizerVersion_configurationHash_runType:unique}});if(existing)return existing;
  const [forebetRows,statareaRows]=await Promise.all([prisma.forebetObservation.findMany({where:{snapshotId:forebet.id},select:identitySelect,orderBy:{id:"asc"}}),prisma.statareaRawRow.findMany({where:{snapshotId:statarea.id},select:identitySelect,orderBy:{id:"asc"}})]);const result=reconcileIdentities(forebetRows,statareaRows);const candidateIds=new Map(result.candidates.map((candidate)=>[candidate.key,randomUUID()]));const count=(status:string)=>result.decisions.filter((decision)=>decision.status===status).length;const selected=result.decisions.filter((decision)=>decision.status==="MATCHED").map((decision)=>result.candidates.find((candidate)=>candidate.key===decision.candidateKey)?.stage);const id=randomUUID();
  await prisma.$transaction(async(tx)=>{await tx.matchRun.create({data:{id,...unique,datasetId,forebetSha256:forebet.contentHash,statareaSha256:statarea.contentHash,configurationJson:JSON.stringify(MATCH_CONFIGURATION),status:"COMPLETED",forebetInputCount:forebetRows.length,statareaInputCount:statareaRows.length,matchedCount:count("MATCHED"),ambiguousCount:count("AMBIGUOUS"),onlyForebetCount:count("ONLY_FOREBET"),onlyStatareaCount:count("ONLY_STATAREA"),conflictCount:count("CONFLICT"),exactCount:selected.filter((stage)=>stage==="EXACT").length,conservativeCount:selected.filter((stage)=>stage==="CONSERVATIVE").length,approximateCount:selected.filter((stage)=>stage==="APPROXIMATE").length,warningsJson:"[]",exportPath:`var/exports/history/${HISTORY_CODE}/days/${date}.json`}});if(result.candidates.length)await tx.matchCandidate.createMany({data:result.candidates.map((candidate)=>({id:candidateIds.get(candidate.key)!,runId:id,forebetObservationId:candidate.forebetId,statareaRowId:candidate.statareaId,orientation:candidate.orientation,homeScore:candidate.homeScore,awayScore:candidate.awayScore,competitionEvidence:candidate.competitionEvidence,countryEvidence:candidate.countryEvidence,categoryEvidence:candidate.categoryEvidence,aggregateScore:candidate.aggregateScore,marginToSecond:candidate.marginToSecond,stage:candidate.stage,evidenceJson:JSON.stringify(candidate.evidence),rejectionReasonsJson:JSON.stringify(candidate.rejectionReasons),rank:candidate.rank}))});await tx.matchDecision.createMany({data:result.decisions.map((decision)=>({id:randomUUID(),runId:id,status:decision.status,forebetObservationId:decision.forebetId,statareaRowId:decision.statareaId,selectedCandidateId:decision.candidateKey?candidateIds.get(decision.candidateKey)??null:null,reasonCode:decision.reasonCode,reasonsJson:JSON.stringify(decision.reasons),warningsJson:JSON.stringify(decision.warnings),confidenceClass:decision.confidenceClass}))});await tx.matchRunAttempt.create({data:{runId:id,status:"COMPLETED"}})});return prisma.matchRun.findUniqueOrThrow({where:{id}})
}

export async function importHistory(from:string,to:string,{prisma=database,throughDate}: {prisma?:PrismaClient;throughDate?:string}={}){
  validateHistoryRange(from,to);if(throughDate!==undefined&&throughDate!==HISTORY_FROM)throw new Error("PREFLIGHT_THROUGH_DATE_MUST_BE_HISTORY_FROM");const dates=historyDates();const datasetId="ou25-july-2026-v1";const importRunId=randomUUID();let requests=0;let retries=0;let lastRequestStarted=0;const beforeRequest=async()=>{const remaining=CAPTURE_MINIMUM_PAUSE_MS-(Date.now()-lastRequestStarted);if(lastRequestStarted&&remaining>0)await wait(remaining);lastRequestStarted=Date.now();requests++};
  const dataset=await prisma.historicalDataset.findUnique({where:{code_version:{code:HISTORY_CODE,version:HISTORY_VERSION}}});if(!dataset)throw new Error("HISTORICAL_DATASET_MISSING");const frozen=await prisma.historicalDatasetState.findFirst({where:{datasetId,status:"FROZEN"},orderBy:{createdAt:"desc"}});
  if(frozen){await prisma.historicalImportRun.create({data:{id:importRunId,datasetId,requestedDatesJson:JSON.stringify(dates),initialCompletedDates:21,networkRequestCount:0,warningsJson:"[]"}});await prisma.historicalDatasetState.create({data:{datasetId,status:"REUSED",completedDates:21,failedDates:0,manifestHash:frozen.manifestHash,manifestExportPath:frozen.manifestExportPath,detailsJson:JSON.stringify({networkRequestCount:0})}});await audit(prisma,datasetId,importRunId,"DATASET_REUSED",{manifestHash:frozen.manifestHash,networkRequestCount:0});return{status:"REUSED" as const,datasetId,manifestHash:frozen.manifestHash!,networkRequestCount:0,retries:0}}
  const initialCompleted=await prisma.historicalDatasetDay.count({where:{datasetId}});const modernProfiles=await ensureModernStatareaProfiles(prisma);const policyCreated=await ensureLegacyRecoveryPolicy(prisma,datasetId);await audit(prisma,datasetId,importRunId,"LEGACY_RECOVERY_STARTED",{capturePolicyVersion:CAPTURE_POLICY_VERSION,modernProfilesCreated:modernProfiles});if(modernProfiles)await audit(prisma,datasetId,importRunId,"MODERN_PROFILES_CREATED",{count:modernProfiles});if(policyCreated)await audit(prisma,datasetId,importRunId,"LEGACY_CLIENT_ENABLED",{sourcePresentation:"LEGACY_OFFICIAL",endpoint:STATAREA_LEGACY_ENDPOINT_TEMPLATE,parserVersion:STATAREA_LEGACY_PARSER_VERSION});
  try{
    for(const date of dates){if(await prisma.historicalDatasetDay.findUnique({where:{datasetId_sportsDate:{datasetId,sportsDate:dv(date)}}}))continue;let forebet=await findForebet(prisma,date);let legacy=await findLegacy(prisma,date);
      if(forebet){await prisma.historicalImportTask.create({data:{importRunId,datasetId,sportsDate:dv(date),source:"FOREBET",snapshotId:forebet.id,state:"REUSED",reason:date===HISTORY_TO?"PINNED_B002_2026_07_21":"RECOVERY_REUSED_REAL_CAPTURE"}});await audit(prisma,datasetId,importRunId,"FOREBET_SNAPSHOT_REUSED",{snapshotId:forebet.id,hash:forebet.contentHash,parserVersion:forebet.parserVersion},date,"FOREBET")}
      else{let lastError:unknown;for(let attempt=0;attempt<2;attempt++){try{await beforeRequest();await captureForebetOu25(date,{prisma});forebet=await findForebet(prisma,date);break}catch(error){lastError=error;if(!retryable(error)||attempt===1)break;retries++}}if(!forebet){await prisma.historicalImportTask.create({data:{importRunId,datasetId,sportsDate:dv(date),source:"FOREBET",state:"FAILED",reason:lastError instanceof Error?lastError.message:"CAPTURE_FAILED"}});throw lastError??new Error("FOREBET_SNAPSHOT_NOT_CREATED")}await prisma.historicalImportTask.create({data:{importRunId,datasetId,sportsDate:dv(date),source:"FOREBET",snapshotId:forebet.id,state:"COMPLETED",reason:"FIRST_VALID_HTTP_CAPTURE"}});await audit(prisma,datasetId,importRunId,"FOREBET_SNAPSHOT_CREATED",{snapshotId:forebet.id,hash:forebet.contentHash,parserVersion:forebet.parserVersion},date,"FOREBET")}
      if(!legacy){let lastError:unknown;await audit(prisma,datasetId,importRunId,"LEGACY_TASK_STARTED",{sourcePresentation:"LEGACY_OFFICIAL",endpoint:`https://old.statarea.com/predictions/${date}`,parserVersion:STATAREA_LEGACY_PARSER_VERSION},date,"STATAREA");for(let attempt=0;attempt<2;attempt++){try{await beforeRequest();await captureLegacyStatarea(date,{prisma});legacy=await findLegacy(prisma,date);if(legacy)await audit(prisma,datasetId,importRunId,"LEGACY_CAPTURE_RECEIVED",{sourcePresentation:"LEGACY_OFFICIAL",snapshotId:legacy.id,hash:legacy.contentHash,parserVersion:legacy.parserVersion,endpoint:legacy.profile.finalUrl,counts:{found:legacy.rowsFound,valid:legacy.validRows,rejected:legacy.rejectedRows,warnings:legacy.warningCount}},date,"STATAREA");break}catch(error){lastError=error;if(!retryable(error)||attempt===1)break;retries++}}if(!legacy){await prisma.historicalImportTask.create({data:{importRunId,datasetId,sportsDate:dv(date),source:"STATAREA",sourcePresentation:"LEGACY_OFFICIAL",state:"FAILED",reason:lastError instanceof Error?lastError.message:"CAPTURE_FAILED"}});await audit(prisma,datasetId,importRunId,"LEGACY_TASK_FAILED",{error:lastError instanceof Error?lastError.message:"CAPTURE_FAILED",sourcePresentation:"LEGACY_OFFICIAL"},date,"STATAREA");throw lastError??new Error("LEGACY_SNAPSHOT_NOT_CREATED")}await prisma.historicalImportTask.create({data:{importRunId,datasetId,sportsDate:dv(date),source:"STATAREA",sourcePresentation:"LEGACY_OFFICIAL",snapshotId:legacy.id,state:"COMPLETED",reason:"FIRST_VALID_HTTP_CAPTURE"}});await audit(prisma,datasetId,importRunId,"LEGACY_SNAPSHOT_CREATED",{sourcePresentation:"LEGACY_OFFICIAL",snapshotId:legacy.id,profileId:legacy.profile.id,hash:legacy.contentHash,parserVersion:legacy.parserVersion,endpoint:legacy.profile.finalUrl},date,"STATAREA")}
      else{await prisma.historicalImportTask.create({data:{importRunId,datasetId,sportsDate:dv(date),source:"STATAREA",sourcePresentation:"LEGACY_OFFICIAL",snapshotId:legacy.id,state:"REUSED",reason:"RESUME_LEGACY_CAPTURE"}});await audit(prisma,datasetId,importRunId,"LEGACY_SNAPSHOT_REUSED",{sourcePresentation:"LEGACY_OFFICIAL",snapshotId:legacy.id,profileId:legacy.profile.id,hash:legacy.contentHash},date,"STATAREA")}
      const duplicate=await prisma.historicalDatasetDay.findFirst({where:{datasetId,OR:[{forebetSha256:forebet.contentHash},{statareaSha256:legacy.contentHash}]}});if(duplicate)throw new Error(`CROSS_DATE_HASH_REUSE:${date}`);const matchRun=await createHistoricalMatchRun(prisma,datasetId,date,forebet,legacy);await prisma.historicalDatasetDay.create({data:{id:randomUUID(),datasetId,sportsDate:dv(date),partition:historyPartition(date),forebetSnapshotId:forebet.id,forebetSha256:forebet.contentHash,statareaSnapshotId:legacy.id,statareaSha256:legacy.contentHash,forebetParserVersion:forebet.parserVersion,statareaParserVersion:legacy.parserVersion,statareaProfileId:legacy.profile.id,statareaSourcePresentation:"LEGACY_OFFICIAL",matchRunId:matchRun.id,sourceCountsJson:JSON.stringify({forebet:{found:forebet.rowsFound,valid:forebet.validRows,rejected:forebet.rejectedRows,warnings:forebet.warningCount},statarea:{found:legacy.rowsFound,valid:legacy.validRows,rejected:legacy.rejectedRows,warnings:legacy.warningCount,unverifiedColumns:5}}),matchCountsJson:JSON.stringify({matched:matchRun.matchedCount,ambiguous:matchRun.ambiguousCount,onlyForebet:matchRun.onlyForebetCount,onlyStatarea:matchRun.onlyStatareaCount,conflict:matchRun.conflictCount,exact:matchRun.exactCount,conservative:matchRun.conservativeCount,approximate:matchRun.approximateCount}),qualityStatus:forebet.rejectedRows||legacy.rejectedRows?"PARTIAL":legacy.validRows===0?"EMPTY_VALID":"COMPLETE",selectionReasonsJson:JSON.stringify(["FOREBET_FIRST_REAL_OR_PINNED","STATAREA_LEGACY_FIRST_VALID"]),warningsJson:JSON.stringify([])}});await audit(prisma,datasetId,importRunId,"HISTORICAL_MATCHING_EXECUTED",{matchRunId:matchRun.id,matcherVersion:MATCHER_VERSION,configurationHash:MATCH_CONFIGURATION_HASH,counts:{matched:matchRun.matchedCount,ambiguous:matchRun.ambiguousCount,conflict:matchRun.conflictCount}},date);await audit(prisma,datasetId,importRunId,"DAY_COMPLETED",{forebetSnapshotId:forebet.id,statareaSnapshotId:legacy.id,sourcePresentation:"LEGACY_OFFICIAL",matchRunId:matchRun.id},date)
      if(throughDate===date)break;
    }
    if(throughDate){const completed=await prisma.historicalDatasetDay.count({where:{datasetId}});await prisma.historicalDatasetState.create({data:{datasetId,status:"PARTIAL",completedDates:completed,failedDates:0,detailsJson:JSON.stringify({preflight:true,throughDate,networkRequestCount:requests})}});await prisma.historicalImportRun.create({data:{id:importRunId,datasetId,requestedDatesJson:JSON.stringify([throughDate]),initialCompletedDates:initialCompleted,networkRequestCount:requests,warningsJson:"[]"}});await audit(prisma,datasetId,importRunId,"DAY_ONE_PREFLIGHT_COMPLETED",{throughDate,completedDates:completed,networkRequestCount:requests,retries});return{status:"PARTIAL_PREFLIGHT" as const,datasetId,completedDates:completed,networkRequestCount:requests,retries}}
    const days=await prisma.historicalDatasetDay.findMany({where:{datasetId},include:{},orderBy:{sportsDate:"asc"}});if(days.length!==21||days.some((day)=>day.statareaSourcePresentation!=="LEGACY_OFFICIAL"||day.statareaParserVersion!==STATAREA_LEGACY_PARSER_VERSION))throw new Error("FROZEN_REQUIRES_21_LEGACY_DAYS");const runs=await prisma.matchRun.findMany({where:{id:{in:days.map((day)=>day.matchRunId)}}});const discoveryMatched=runs.filter((run)=>run.sportDate.toISOString().slice(0,10)<=DISCOVERY_TO).reduce((sum,run)=>sum+run.matchedCount,0);const validationMatched=runs.filter((run)=>run.sportDate.toISOString().slice(0,10)>=VALIDATION_FROM).reduce((sum,run)=>sum+run.matchedCount,0);if(!discoveryMatched||!validationMatched)throw new Error("PARTITION_WITH_ZERO_MATCHES");const manifestA=await buildHistoricalManifest(datasetId,prisma);const manifestB=await buildHistoricalManifest(datasetId,prisma);const manifestHash=canonicalHash(manifestA);if(manifestHash!==canonicalHash(manifestB))throw new Error("MANIFEST_HASH_NOT_REPRODUCIBLE");const exports=await preserveHistoryExports(HISTORY_CODE,manifestA,manifestHash,prisma);await prisma.historicalDatasetState.create({data:{datasetId,status:"FROZEN",completedDates:21,failedDates:0,manifestHash,manifestExportPath:exports.manifestPath,detailsJson:JSON.stringify({exports,capturePolicyVersion:CAPTURE_POLICY_VERSION})}});await prisma.historicalImportRun.create({data:{id:importRunId,datasetId,requestedDatesJson:JSON.stringify(dates),initialCompletedDates:initialCompleted,networkRequestCount:requests,warningsJson:"[]"}});await audit(prisma,datasetId,importRunId,"MANIFEST_GENERATED",{manifestHash,exports:exports.count});await audit(prisma,datasetId,importRunId,"CONTRACT_VALIDATED",{zod:true,ajv:true,canonical:true});await audit(prisma,datasetId,importRunId,"DATASET_FROZEN",{manifestHash,completedDates:21,networkRequestCount:requests,retries});return{status:"FROZEN" as const,datasetId,manifestHash,networkRequestCount:requests,retries,manifest:manifestA}
  }catch(error){const completed=await prisma.historicalDatasetDay.count({where:{datasetId}});await prisma.historicalDatasetState.create({data:{datasetId,status:"PARTIAL",completedDates:completed,failedDates:1,detailsJson:JSON.stringify({error:error instanceof Error?error.message:"UNKNOWN"})}});await prisma.historicalImportRun.create({data:{id:importRunId,datasetId,requestedDatesJson:JSON.stringify(dates),initialCompletedDates:initialCompleted,networkRequestCount:requests,warningsJson:JSON.stringify([error instanceof Error?error.message:"UNKNOWN"])}});await audit(prisma,datasetId,importRunId,"BATCH_STOPPED",{completed,error:error instanceof Error?error.message:"UNKNOWN",networkRequestCount:requests,retries});throw error}
}
