import { randomUUID } from "node:crypto";
import { canonicalHash } from "@/domain/canonical-hash";
import { MATCH_CONFIGURATION, MATCH_CONFIGURATION_HASH, MATCHER_VERSION, NORMALIZER_VERSION, RECONCILIATION_DATE } from "@/domain/reconciliation/configuration";
import { reconcileIdentities, type IdentityRow } from "@/domain/reconciliation/matcher";
import { normalizeIdentity } from "@/domain/reconciliation/normalizer";
import { database } from "@/infrastructure/database";
import { preserveReconciliationExport } from "@/infrastructure/reconciliation/export-store";

const warning = "La fuente Statarea presentó variación de contenido entre capturas de la misma fecha. La conciliación está fijada a snapshots específicos.";
const date = new Date(`${RECONCILIATION_DATE}T00:00:00.000Z`);
const identitySelect = { id: true, homeTeamRaw: true, awayTeamRaw: true, competitionRaw: true, countryRaw: true, categoryRaw: true } as const;

async function audit(runId: string | null, eventType: string, details: unknown) { await database.matchAuditEvent.create({ data: { runId, eventType, detailsJson: JSON.stringify(details) } }); }

async function createOrReuseRun(forebetSnapshot: { id: string; contentHash: string }, statareaSnapshot: { id: string; contentHash: string }, runType: "PRIMARY" | "STABILITY_DIAGNOSTIC") {
  const identity = { sportDate: date, forebetSnapshotId: forebetSnapshot.id, statareaSnapshotId: statareaSnapshot.id, matcherVersion: MATCHER_VERSION, normalizerVersion: NORMALIZER_VERSION, configurationHash: MATCH_CONFIGURATION_HASH, runType };
  const existing = await database.matchRun.findUnique({ where: { sportDate_forebetSnapshotId_statareaSnapshotId_matcherVersion_normalizerVersion_configurationHash_runType: identity } });
  if (existing) { await database.matchRunAttempt.create({ data: { runId: existing.id, status: "REUSED" } }); await audit(existing.id, "RUN_REUSED", identity); return { run: existing, reused: true }; }
  await audit(null, "RECONCILIATION_STARTED", identity); await audit(null, "SNAPSHOTS_FIXED", { ...identity, forebetSha256: forebetSnapshot.contentHash, statareaSha256: statareaSnapshot.contentHash }); await audit(null, "CONFIGURATION_FIXED", { configurationHash: MATCH_CONFIGURATION_HASH, matcherVersion: MATCHER_VERSION, normalizerVersion: NORMALIZER_VERSION });
  const [forebet, statarea] = await Promise.all([database.forebetObservation.findMany({ where: { snapshotId: forebetSnapshot.id }, select: identitySelect, orderBy: { id: "asc" } }), database.statareaRawRow.findMany({ where: { snapshotId: statareaSnapshot.id }, select: identitySelect, orderBy: { id: "asc" } })]);
  const outcome = reconcileIdentities(forebet, statarea); const candidateIds = new Map(outcome.candidates.map((candidate) => [candidate.key, randomUUID()]));
  const count = (status: string) => outcome.decisions.filter((decision) => decision.status === status).length;
  const selectedStages = outcome.decisions.filter((decision) => decision.status === "MATCHED").map((decision) => outcome.candidates.find((candidate) => candidate.key === decision.candidateKey)?.stage);
  const runId = randomUUID(); const exportPath = `var/exports/reconciliation/${RECONCILIATION_DATE}/${runId}.json`;
  await database.$transaction(async (tx) => {
    await tx.matchRun.create({ data: { id: runId, ...identity, forebetSha256: forebetSnapshot.contentHash, statareaSha256: statareaSnapshot.contentHash, configurationJson: JSON.stringify(MATCH_CONFIGURATION), status: "COMPLETED", forebetInputCount: forebet.length, statareaInputCount: statarea.length, matchedCount: count("MATCHED"), ambiguousCount: count("AMBIGUOUS"), onlyForebetCount: count("ONLY_FOREBET"), onlyStatareaCount: count("ONLY_STATAREA"), conflictCount: count("CONFLICT"), exactCount: selectedStages.filter((stage) => stage === "EXACT").length, conservativeCount: selectedStages.filter((stage) => stage === "CONSERVATIVE").length, approximateCount: selectedStages.filter((stage) => stage === "APPROXIMATE").length, warningsJson: JSON.stringify([warning]), exportPath } });
    await tx.matchCandidate.createMany({ data: outcome.candidates.map((candidate) => ({ id: candidateIds.get(candidate.key)!, runId, forebetObservationId: candidate.forebetId, statareaRowId: candidate.statareaId, orientation: candidate.orientation, homeScore: candidate.homeScore, awayScore: candidate.awayScore, competitionEvidence: candidate.competitionEvidence, countryEvidence: candidate.countryEvidence, categoryEvidence: candidate.categoryEvidence, aggregateScore: candidate.aggregateScore, marginToSecond: candidate.marginToSecond, stage: candidate.stage, evidenceJson: JSON.stringify(candidate.evidence), rejectionReasonsJson: JSON.stringify(candidate.rejectionReasons), rank: candidate.rank })) });
    await tx.matchDecision.createMany({ data: outcome.decisions.map((decision) => ({ id: randomUUID(), runId, status: decision.status, forebetObservationId: decision.forebetId, statareaRowId: decision.statareaId, selectedCandidateId: decision.candidateKey ? candidateIds.get(decision.candidateKey) ?? null : null, reasonCode: decision.reasonCode, reasonsJson: JSON.stringify(decision.reasons), warningsJson: JSON.stringify(decision.warnings), confidenceClass: decision.confidenceClass })) });
    await tx.matchRunAttempt.create({ data: { runId, status: "COMPLETED" } });
  });
  await audit(runId, "CANDIDATES_GENERATED", { count: outcome.candidates.length }); await audit(runId, "DECISIONS_GENERATED", { matched: count("MATCHED"), ambiguous: count("AMBIGUOUS"), conflict: count("CONFLICT") }); await audit(runId, "RUN_COMPLETED", { runId });
  return { run: await database.matchRun.findUniqueOrThrow({ where: { id: runId } }), reused: false };
}

async function stabilityFor(runs: Awaited<ReturnType<typeof createOrReuseRun>>["run"][], statareaSnapshots: Array<{ id: string }>) {
  const rows = await Promise.all(statareaSnapshots.map((snapshot) => database.statareaRawRow.findMany({ where: { snapshotId: snapshot.id }, select: identitySelect })));
  const sets = rows.map((group) => new Set(group.map((row) => `${normalizeIdentity(row.homeTeamRaw)}|${normalizeIdentity(row.awayTeamRaw)}`))); const union = new Set(sets.flatMap((set) => [...set]));
  const matchedSets = await Promise.all(runs.map(async (run) => { const decisions = await database.matchDecision.findMany({ where: { runId: run.id, status: "MATCHED" } }); const s = await database.statareaRawRow.findMany({ where: { id: { in: decisions.map((decision) => decision.statareaRowId!) } }, select: identitySelect }); const byId = new Map(s.map((row) => [row.id, row])); return new Set(decisions.map((decision) => { const row = byId.get(decision.statareaRowId!)!; return `${decision.forebetObservationId}|${normalizeIdentity(row.homeTeamRaw)}|${normalizeIdentity(row.awayTeamRaw)}`; })); }));
  const common = [...matchedSets[0]].filter((key) => matchedSets.slice(1).every((set) => set.has(key))); const coverageByRun = runs.map((run) => ({ runId: run.id, forebet: run.forebetInputCount ? run.matchedCount / run.forebetInputCount : 0, statarea: run.statareaInputCount ? run.matchedCount / run.statareaInputCount : 0 }));
  return { presentInAllSnapshots: [...union].filter((key) => sets.every((set) => set.has(key))).length, presentInOneOrTwo: [...union].filter((key) => !sets.every((set) => set.has(key))).length, commonMatches: common.length, primaryOnlyMatches: [...matchedSets[0]].filter((key) => !matchedSets[1].has(key) && !matchedSets[2].has(key)).length, coverageByRun, changedStates: Math.max(...runs.map((run) => run.matchedCount)) - Math.min(...runs.map((run) => run.matchedCount)), newConflicts: Math.max(0, ...runs.slice(1).map((run) => run.conflictCount - runs[0].conflictCount)), newAmbiguous: Math.max(0, ...runs.slice(1).map((run) => run.ambiguousCount - runs[0].ambiguousCount)) };
}

async function buildContract(runId: string, stability: Awaited<ReturnType<typeof stabilityFor>> | null) {
  const run = await database.matchRun.findUniqueOrThrow({ where: { id: runId }, include: { candidates: { orderBy: [{ forebetObservationId: "asc" }, { rank: "asc" }] }, decisions: { orderBy: { id: "asc" } } } });
  const [forebetSnapshot, statareaSnapshot, forebetRows, statareaRows] = await Promise.all([database.forebetCaptureSnapshot.findUniqueOrThrow({ where: { id: run.forebetSnapshotId } }), database.statareaCaptureSnapshot.findUniqueOrThrow({ where: { id: run.statareaSnapshotId } }), database.forebetObservation.findMany({ where: { snapshotId: run.forebetSnapshotId }, select: identitySelect }), database.statareaRawRow.findMany({ where: { snapshotId: run.statareaSnapshotId }, select: identitySelect })]);
  const f = new Map(forebetRows.map((row) => [row.id, row])); const s = new Map(statareaRows.map((row) => [row.id, row]));
  const side = (row: IdentityRow | undefined) => ({ homeRaw: row?.homeTeamRaw ?? null, awayRaw: row?.awayTeamRaw ?? null, competitionRaw: row?.competitionRaw ?? null, countryRaw: row?.countryRaw ?? null, homeNormalized: row ? normalizeIdentity(row.homeTeamRaw) : null, awayNormalized: row ? normalizeIdentity(row.awayTeamRaw) : null });
  return { contractVersion: "1.0" as const, matchRun: { id: run.id, sportDate: RECONCILIATION_DATE, runType: run.runType, status: run.status, matcherVersion: run.matcherVersion, normalizerVersion: run.normalizerVersion, configurationHash: run.configurationHash, createdAt: run.createdAt.toISOString() }, sourceSnapshots: { forebet: { id: forebetSnapshot.id, sha256: forebetSnapshot.contentHash, rowCount: run.forebetInputCount }, statarea: { id: statareaSnapshot.id, sha256: statareaSnapshot.contentHash, rowCount: run.statareaInputCount } }, configuration: { code: "OU25-MATCHER" as const, status: "DRAFT" as const, hash: run.configurationHash, value: MATCH_CONFIGURATION }, counts: { forebetInput: run.forebetInputCount, statareaInput: run.statareaInputCount, matched: run.matchedCount, ambiguous: run.ambiguousCount, onlyForebet: run.onlyForebetCount, onlyStatarea: run.onlyStatareaCount, conflict: run.conflictCount, exact: run.exactCount, conservative: run.conservativeCount, approximate: run.approximateCount }, coverage: { forebet: run.forebetInputCount ? run.matchedCount / run.forebetInputCount : 0, statarea: run.statareaInputCount ? run.matchedCount / run.statareaInputCount : 0 }, decisions: run.decisions.map((decision) => ({ id: decision.id, status: decision.status, forebetObservationId: decision.forebetObservationId, statareaRowId: decision.statareaRowId, selectedCandidateId: decision.selectedCandidateId, reasonCode: decision.reasonCode, reasons: JSON.parse(decision.reasonsJson), warnings: JSON.parse(decision.warningsJson), confidenceClass: decision.confidenceClass, identity: { forebet: side(f.get(decision.forebetObservationId ?? "")), statarea: side(s.get(decision.statareaRowId ?? "")) } })), candidates: run.candidates.map((candidate) => ({ id: candidate.id, forebetObservationId: candidate.forebetObservationId!, statareaRowId: candidate.statareaRowId!, orientation: candidate.orientation, homeScore: candidate.homeScore, awayScore: candidate.awayScore, aggregateScore: candidate.aggregateScore, marginToSecond: candidate.marginToSecond, stage: candidate.stage as "EXACT" | "CONSERVATIVE" | "APPROXIMATE" | "CONFLICT", rank: candidate.rank, evidence: JSON.parse(candidate.evidenceJson), rejectionReasons: JSON.parse(candidate.rejectionReasonsJson) })), stabilityDiagnostic: stability, warnings: JSON.parse(run.warningsJson), generatedAt: run.createdAt.toISOString() };
}

export async function reconcileFixtures(dateInput: string) {
  if (dateInput !== RECONCILIATION_DATE) throw new Error("DATE_NOT_AUTHORIZED");
  const forebet = await database.forebetCaptureSnapshot.findFirst({ where: { requestedDate: date } }); if (!forebet || forebet.contentHash !== "41539d0e0e1ec9a5dadd7a144a79e5d14a31878a5de0fedffdf54c20c9946c6b") throw new Error("FOREBET_SNAPSHOT_NOT_FIXED");
  const successful = await database.statareaCaptureAttempt.findMany({ where: { requestedDate: date, status: "SUCCEEDED", snapshotId: { not: null } }, orderBy: { capturedAt: "asc" }, include: { snapshot: true } });
  const snapshots = successful.map((attempt) => attempt.snapshot!).filter((snapshot, index, all) => all.findIndex((entry) => entry.id === snapshot.id) === index); if (snapshots.length !== 3) throw new Error("STATAREA_SNAPSHOT_SET_INVALID");
  const primary = snapshots.at(-1)!; const ordered = [primary, snapshots[0], snapshots[1]];
  const runResults = []; for (const [index, snapshot] of ordered.entries()) runResults.push(await createOrReuseRun(forebet, snapshot, index === 0 ? "PRIMARY" : "STABILITY_DIAGNOSTIC"));
  const runs = runResults.map((result) => result.run); const stability = await stabilityFor(runs, snapshots); const reportHash = canonicalHash(stability); const stabilityPath = `var/exports/reconciliation/${RECONCILIATION_DATE}/stability-${runs[0].id}.json`;
  const existingReport = await database.matchStabilityReport.findUnique({ where: { primaryRunId_reportHash: { primaryRunId: runs[0].id, reportHash } } }); if (!existingReport) { await database.matchStabilityReport.create({ data: { sportDate: date, primaryRunId: runs[0].id, alternativeRunIdsJson: JSON.stringify(runs.slice(1).map((run) => run.id)), reportHash, reportJson: JSON.stringify(stability), exportPath: stabilityPath } }); await audit(runs[0].id, "STABILITY_DIAGNOSTIC_GENERATED", stability); }
  for (const [index, run] of runs.entries()) { const contract = await buildContract(run.id, index === 0 ? stability : null); await preserveReconciliationExport(RECONCILIATION_DATE, run.id, contract); if (!runResults[index].reused) { await audit(run.id, "EXPORT_GENERATED", { exportPath: run.exportPath }); await audit(run.id, "CONTRACT_VALIDATED", { zod: true, ajv: true }); } }
  const stabilityContract = await buildContract(runs[0].id, stability); await preserveReconciliationExport(RECONCILIATION_DATE, `stability-${runs[0].id}`, stabilityContract);
  return { runs, reused: runResults.map((result) => result.reused), stability, configurationHash: MATCH_CONFIGURATION_HASH, primarySnapshotId: primary.id };
}
